reverting to functions+calls

diff --git a/expandfs b/expandfs
--- a/expandfs
+++ b/expandfs
@@ -151,7 +151,7 @@ echo ""
 
 if confirm "Do you wish to continue?"; then
 
-    #get_init_sys function fron raspi-config
+    get_init_sys() {
     if command -v systemctl > /dev/null && systemctl | grep -q '\-\.mount'; then
         SYSTEMD=1
     elif [ -f /etc/init.d/cron ] && [ ! -h /etc/init.d/cron ]; then
@@ -160,39 +160,41 @@ if confirm "Do you wish to continue?"; then
         echo "Unrecognised init system"
         return 1
     fi
+    }
 
-    #do_expand_rootfs function fron raspi-config
-    if [ $SYSTEMD -eq 1 ]; then
-        ROOT_PART=$(mount | sed -n 's|^/dev/\(.*\) on / .*|\1|p')
-    else
-        if ! [ -h /dev/root ]; then
-            echo -e "/dev/root does not exist or is not a symlink. Don't know how to expand"
+    do_expand_rootfs() {
+        get_init_sys
+        if [ $SYSTEMD -eq 1 ]; then
+            ROOT_PART=$(mount | sed -n 's|^/dev/\(.*\) on / .*|\1|p')
+        else
+            if ! [ -h /dev/root ]; then
+                echo -e "/dev/root does not exist or is not a symlink. Don't know how to expand"
+                return 0
+            fi
+            ROOT_PART=$(readlink /dev/root)
+        fi
+        PART_NUM=${ROOT_PART#mmcblk0p}
+        if [ "$PART_NUM" = "$ROOT_PART" ]; then
+            echo -e "$ROOT_PART is not an SD card. Don't know how to expand"
             return 0
         fi
-        ROOT_PART=$(readlink /dev/root)
-    fi
-    PART_NUM=${ROOT_PART#mmcblk0p}
-    if [ "$PART_NUM" = "$ROOT_PART" ]; then
-        echo -e "$ROOT_PART is not an SD card. Don't know how to expand"
-        return 0
-    fi
-    # NOTE: the NOOBS partition layout confuses parted. For now, let's only 
-    # agree to work with a sufficiently simple partition layout
-    if [ "$PART_NUM" -ne 2 ]; then
-        echo -e "Your partition layout is not currently supported by this tool. You are probably using NOOBS, in which case your root filesystem is already expanded anyway."
-        return 0
-    fi
-    LAST_PART_NUM=$(parted /dev/mmcblk0 -ms unit s p | tail -n 1 | cut -f 1 -d:)
-    if [ $LAST_PART_NUM -ne $PART_NUM ]; then
-        echo -e "$ROOT_PART is not the last partition. Don't know how to expand"
-        return 0
-    fi
-    # Get the starting offset of the root partition
-    PART_START=$(parted /dev/mmcblk0 -ms unit s p | grep "^${PART_NUM}" | cut -f 2 -d: | sed 's/[^0-9]//g')
-    [ "$PART_START" ] || return 1
-    # Return value will likely be error for fdisk as it fails to reload the
-    # partition table because the root fs is mounted
-    fdisk /dev/mmcblk0 <<EOF
+        # NOTE: the NOOBS partition layout confuses parted. For now, let's only 
+        # agree to work with a sufficiently simple partition layout
+        if [ "$PART_NUM" -ne 2 ]; then
+            echo -e "Your partition layout is not currently supported by this tool. You are probably using NOOBS, in which case your root filesystem is already expanded anyway."
+            return 0
+        fi
+        LAST_PART_NUM=$(parted /dev/mmcblk0 -ms unit s p | tail -n 1 | cut -f 1 -d:)
+        if [ $LAST_PART_NUM -ne $PART_NUM ]; then
+            echo -e "$ROOT_PART is not the last partition. Don't know how to expand"
+            return 0
+        fi
+        # Get the starting offset of the root partition
+        PART_START=$(parted /dev/mmcblk0 -ms unit s p | grep "^${PART_NUM}" | cut -f 2 -d: | sed 's/[^0-9]//g')
+        [ "$PART_START" ] || return 1
+        # Return value will likely be error for fdisk as it fails to reload the
+        # partition table because the root fs is mounted
+        fdisk /dev/mmcblk0 <<EOF
 p
 d
 $PART_NUM
@@ -204,9 +206,9 @@ $PART_START
 p
 w
 EOF
-    ASK_TO_REBOOT=1
-    # now set up an init.d script
-    cat <<EOF > /etc/init.d/resize2fs_once &&
+        ASK_TO_REBOOT=1
+        # now set up an init.d script
+        cat <<EOF > /etc/init.d/resize2fs_once &&
 #!/bin/sh
 ### BEGIN INIT INFO
 # Provides:          resize2fs_once
@@ -234,11 +236,13 @@ case "\$1" in
     ;;
 esac
 EOF
-    chmod +x /etc/init.d/resize2fs_once &&
-    update-rc.d resize2fs_once defaults &&
-    if [ "$INTERACTIVE" = True ]; then
-        echo -e "Root partition has been resized.\nThe filesystem will be enlarged upon the next reboot"
-    fi
+        chmod +x /etc/init.d/resize2fs_once &&
+        update-rc.d resize2fs_once defaults &&
+        if [ "$INTERACTIVE" = True ]; then
+            echo -e "Root partition has been resized.\nThe filesystem will be enlarged upon the next reboot"
+        fi
+    }
+    do_expand_rootfs
 
     echo "Messages regarding failure to read the partition table can be ignored."
     echo "You should now reboot your system."
