fetch raspi-gpio from RASPOOL if necessary

diff --git a/installers/blinkt b/installers/blinkt
--- a/installers/blinkt
+++ b/installers/blinkt
@@ -70,7 +70,7 @@ examplesdep=( "numpy" "psutil" "requests" "tweepy" ) # list of python modules re
 somemoredep=() # list of additional dependencies
 xdisplaydep=() # list of dependencies requiring X server
 
-# template 1705170025
+# template 1705171345
 
 FORCE=$1
 ASK_TO_REBOOT=false
@@ -100,6 +100,7 @@ SMBUS35="python3-smbus1_1.1+35dbg-1_armhf.deb"
 SPIDEV2="python-spidev_2.0~git20150907_armhf.deb"
 SPIDEV3="python3-spidev_2.0~git20150907_armhf.deb"
 
+RASPGPIO="raspi-gpio_0.20170105_armhf.deb"
 RPIGPIO2="python-rpi.gpio_0.6.3~jessie-1_armhf.deb"
 RPIGPIO3="python3-rpi.gpio_0.6.3~jessie-1_armhf.deb"
 
@@ -669,9 +670,14 @@ if confirm "Do you wish to continue?"; then
 
     if [ $gpioreq == "yes" ]; then
         echo -e "\nChecking for packages required for GPIO control..."
+        if ! apt_pkg_install "raspi-gpio" &> /dev/null; then
+                echo "package raspi-gpio can't be found, fetching from alternative location..."
+                wget $RPIPOOL/main/r/raspi-gpio/$RASPGPIO &> /dev/null
+                sudo dpkg -i $DEBDIR/$RASPGPIO && FAILED_PKG=false
+        fi
         if [ "$pip2support" == "yes" ] && ! apt_pkg_install "python-rpi.gpio" &> /dev/null; then
             if [ -n $(python --version 2>&1 | grep -q "2.7") ]; then
-                echo "python-rpi.gpio can't be found, fetching from alternative location..."
+                echo "package python-rpi.gpio can't be found, fetching from alternative location..."
                 DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX` && cd $DEBDIR
                 wget $RPIPOOL/main/r/rpi.gpio/$RPIGPIO2 &> /dev/null
                 sudo dpkg -i $DEBDIR/$RPIGPIO2 && FAILED_PKG=false
@@ -681,7 +687,7 @@ if confirm "Do you wish to continue?"; then
         fi
         if [ "$pip3support" == "yes" ] && ! apt_pkg_install "python3-rpi.gpio" &> /dev/null; then
             if [ -n $(python3 --version 2>&1 | grep -q "3.4") ]; then
-                echo "python3-rpi.gpio can't be found, fetching from alternative location..."
+                echo "package python3-rpi.gpio can't be found, fetching from alternative location..."
                 DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX` && cd $DEBDIR
                 wget $RPIPOOL/main/r/rpi.gpio/$RPIGPIO3 &> /dev/null
                 sudo dpkg -i $DEBDIR/$RPIGPIO3 && FAILED_PKG=false
@@ -726,7 +732,7 @@ if confirm "Do you wish to continue?"; then
         echo -e "\nChecking packages required by SPI interface..."
         if [ "$pip2support" == "yes" ] && ! apt_pkg_install "python-spidev" &> /dev/null; then
             if [ -n $(python --version 2>&1 | grep -q "2.7") ]; then
-                echo "python-spidev can't be found, fetching from alternative location..."
+                echo "package python-spidev can't be found, fetching from alternative location..."
                 DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX` && cd $DEBDIR
                 wget $RPIPOOL/main/s/spidev/$SPIDEV2 &> /dev/null
                 sudo dpkg -i $DEBDIR/$SPIDEV2 && FAILED_PKG=false
@@ -736,7 +742,7 @@ if confirm "Do you wish to continue?"; then
         fi
         if [ "$pip3support" == "yes" ] && ! apt_pkg_install "python3-spidev" &> /dev/null; then
             if [ -n $(python3 --version 2>&1 | grep -q "3.4") ]; then
-                echo "python3-spidev can't be found, fetching from alternative location..."
+                echo "package python3-spidev can't be found, fetching from alternative location..."
                 DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX` && cd $DEBDIR
                 wget $RPIPOOL/main/s/spidev/$SPIDEV3 &> /dev/null
                 sudo dpkg -i $DEBDIR/$SPIDEV3 && FAILED_PKG=false
@@ -781,7 +787,7 @@ if confirm "Do you wish to continue?"; then
         echo -e "\nChecking packages required by I2C interface..."
         if [ "$pip2support" == "yes" ] && ! apt_pkg_install "python-smbus" &> /dev/null; then
             if [ -n $(python --version 2>&1 | grep -q "2.7") ]; then
-                echo "python-smbus can't be found, fetching from alternative location..."
+                echo "package python-smbus can't be found, fetching from alternative location..."
                 DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX` && cd $DEBDIR
                 wget $RPIPOOL/main/i/i2c-tools/$SMBUS2 &> /dev/null
                 sudo dpkg -i $DEBDIR/$SMBUS2 && FAILED_PKG=false
@@ -789,13 +795,13 @@ if confirm "Do you wish to continue?"; then
         fi
         if [ "$pip3support" == "yes" ] && ! apt_pkg_install "python3-smbus" &> /dev/null; then
             if [ -n $(python3 --version 2>&1 | grep -q "3.4") ]; then
-                echo "python3-smbus can't be found, fetching from alternative location..."
+                echo "package python3-smbus can't be found, fetching from alternative location..."
                 DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX` && cd $DEBDIR
                 wget $RPIPOOL/main/i/i2c-tools/$SMBUS3 &> /dev/null
                 sudo dpkg -i $DEBDIR/$SMBUS3 && FAILED_PKG=false
             elif [ -n $(python3 --version 2>&1 | grep -q "3.5") ]; then
                 if apt_pkg_req "python3-smbus1" &> /dev/null; then
-                    echo "python3-smbus can't be found, fetching from alternative location..."
+                    echo "package python3-smbus can't be found, fetching from alternative location..."
                     DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX` && cd $DEBDIR
                     wget $GETPOOL/resources/$SMBUS35 &> /dev/null
                     sudo dpkg -i $DEBDIR/$SMBUS35 && FAILED_PKG=false
