inverted logic for pip list check

diff --git a/installers/blinkt b/installers/blinkt
--- a/installers/blinkt
+++ b/installers/blinkt
@@ -71,7 +71,7 @@ moreaptdep=( "python-numpy" "python-psutil" "python-requests" "python-tweepy" "p
 pipdeplist=() # list of dependencies to source from pip
 morepipdep=() # list of additional pip dependencies
 
-# template 1609162240
+# template 1609162255
 
 FORCE=$1
 ASK_TO_REBOOT=false
@@ -502,53 +502,6 @@ if confirm "Do you wish to continue?"; then
         fi
     fi
 
-    if [ $i2creq == "yes" ]; then
-        newline
-        if ls /dev/i2c* &> /dev/null; then
-            success "I2C already enabled"
-        else
-            echo "I2C must be enabled for $productname to work"
-            \curl -sS $GETPOOL/i2c | sudo bash -s - "-y"
-            ASK_TO_REBOOT=true
-        fi
-        newline && echo "Checking packages required by I2C interface..." && newline
-        if apt_pkg_req "python-smbus"; then
-            if ! apt_pkg_install "python-smbus" && python --version | grep "2.7" > /dev/null; then
-                echo "python-smbus can't be found, fetching from alternative location..."
-                DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
-                cd $DEBDIR
-                wget $RASPOOL/main/i/i2c-tools/python-smbus_3.1.1+svn-2_armhf.deb &> /dev/null
-                sudo dpkg -i $DEBDIR/python-smbus_3.1.1+svn-2_armhf.deb
-            fi
-        fi
-        if $PIP2_BIN list | grep "smbus" > /dev/null; then
-            FAILED_PKG=true
-        fi
-        if apt_pkg_req "python3-smbus"; then
-            if ! apt_pkg_install "python3-smbus"; then
-                if python3 --version | grep "3.4" > /dev/null; then
-                    echo "python3-smbus can't be found, fetching from alternative location..."
-                    DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
-                    cd $DEBDIR
-                    wget $RASPOOL/main/i/i2c-tools/python3-smbus_3.1.1+svn-2_armhf.deb &> /dev/null
-                    sudo dpkg -i $DEBDIR/python3-smbus_3.1.1+svn-2_armhf.deb
-                elif python3 --version | grep "3.5" > /dev/null; then
-                    echo "python3-smbus can't be found, fetching from alternative location..."
-                    DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
-                    cd $DEBDIR
-                    wget $GETPOOL/python3-smbus1_1.1+35dbg-1_armhf.deb &> /dev/null
-                    sudo dpkg -i $DEBDIR/python3-smbus1_1.1+35dbg-1_armhf.deb
-                else
-                    warning "Unable to install compatible python3-smbus!"
-                    FAILED_PKG=true
-                fi
-            fi
-        fi
-        if $PIP3_BIN list | grep "smbus" > /dev/null; then
-            FAILED_PKG=true
-        fi
-    fi
-
     if [ $spireq == "yes" ]; then
         newline
         if ls /dev/spi* &> /dev/null; then
@@ -564,6 +517,54 @@ if confirm "Do you wish to continue?"; then
         fi
         if apt_pkg_req "python3-spidev" && ! apt_pkg_install "python3-spidev" &> /dev/null; then
             sudo $PIP3_BIN install spidev -U && FAILED_PKG=false
+        fi
+    fi
+
+    if [ $i2creq == "yes" ]; then
+        newline
+        if ls /dev/i2c* &> /dev/null; then
+            success "I2C already enabled"
+        else
+            echo "I2C must be enabled for $productname to work"
+            \curl -sS $GETPOOL/i2c | sudo bash -s - "-y"
+            ASK_TO_REBOOT=true
+        fi
+        newline && echo "Checking packages required by I2C interface..." && newline
+        if apt_pkg_req "python-smbus"; then
+            if ! apt_pkg_install "python-smbus" && python --version | grep "2.7" > /dev/null; then
+                echo "python-smbus can't be found, fetching from alternative location..."
+                FAILED_PKG=false
+                DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX` && cd $DEBDIR
+                wget $RASPOOL/main/i/i2c-tools/python-smbus_3.1.1+svn-2_armhf.deb &> /dev/null
+                sudo dpkg -i $DEBDIR/python-smbus_3.1.1+svn-2_armhf.deb
+            fi
+        fi
+        if ! $PIP2_BIN list | grep "smbus" > /dev/null; then
+            FAILED_PKG=true
+        fi
+        if apt_pkg_req "python3-smbus"; then
+            if ! apt_pkg_install "python3-smbus"; then
+                if python3 --version | grep "3.4" > /dev/null; then
+                    echo "python3-smbus can't be found, fetching from alternative location..."
+                    FAILED_PKG=false
+                    DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX` && cd $DEBDIR
+                    wget $RASPOOL/main/i/i2c-tools/python3-smbus_3.1.1+svn-2_armhf.deb &> /dev/null
+                    sudo dpkg -i $DEBDIR/python3-smbus_3.1.1+svn-2_armhf.deb
+                elif python3 --version | grep "3.5" > /dev/null; then
+                    echo "python3-smbus can't be found, fetching from alternative location..."
+                    FAILED_PKG=false
+                    DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX` && cd $DEBDIR
+                    wget $GETPOOL/python3-smbus1_1.1+35dbg-1_armhf.deb &> /dev/null
+                    sudo dpkg -i $DEBDIR/python3-smbus1_1.1+35dbg-1_armhf.deb
+                    warning "Unable to install compatible python3-smbus!"
+                else
+                    warning "Unable to install compatible python3-smbus!"
+                    FAILED_PKG=true
+                fi
+            fi
+        fi
+        if ! $PIP3_BIN list | grep "smbus" > /dev/null; then
+            FAILED_PKG=true
         fi
     fi
 
