distro independent handing of RPi.GPIO

diff --git a/installers/blinkt b/installers/blinkt
--- a/installers/blinkt
+++ b/installers/blinkt
@@ -64,15 +64,13 @@ copydir=( "documentation" "examples" ) # subdirectories to copy from repo
 pipdeplist=() # list of dependencies to source from pip
 pkgaptremove=() # list of conflicting apt packages to remove
 pkgdeplist1=() # list core dependencies
-pkgdeplist2=( "python-pip" "python-rpi.gpio" ) # list python 2 dependencies
-pkgdeplist3=( "python3-pip" "python3-rpi.gpio" ) # list python 3 dependencies
-pkgdeplist7=() # list dependencies for Wheezy only
-pkgdeplist8=() # list dependencies for Jessie only
+pkgdeplist2=( "python-pip" ) # list python 2 dependencies
+pkgdeplist3=( "python3-pip" ) # list python 3 dependencies
 moreaptdep=( "git" "python-numpy" "python-psutil" "python-requests" "python-tweepy" "python3-numpy" "python3-psutil" "python3-requests" ) # list of all the additional apt dependencies
 morepipdep=() # list of all the additional pip dependencies
 spacereq=150 # minimum size required on root partition in MB
 
-# template 1609082035
+# template 1609161340
 
 FORCE=$1
 ASK_TO_REBOOT=false
@@ -89,8 +87,9 @@ INITABCONF=/etc/inittab
 BLACKLIST=/etc/modprobe.d/raspi-blacklist.conf
 LOADMOD=/etc/modules
 
-RASPOOL="http://mirrordirector.raspbian.org/raspbian/pool"
 DEBPOOL="http://ftp.debian.org/debian/pool"
+GETPOOL="https://get.pimoroni.com/"
+RASPOOL="http://mirrordirector.raspbian.org/raspbian/pool"
 
 # function define
 
@@ -158,8 +157,7 @@ sysreboot() {
     warning "your computer to reboot to take effect."
     newline
     if prompt "Would you like to reboot now?"; then
-        sync
-        sudo reboot
+        sync && sudo reboot
     fi
 }
 
@@ -271,25 +269,19 @@ get_init_sys() {
 
 i2c_vc_dtparam() {
     if [ -e $CONFIG ] && grep -q "^dtparam=i2c_vc=on$" $CONFIG; then
-        newline
-        echo "i2c0 bus already active"
+        newline && echo "i2c0 bus already active"
     else
-        newline
-        echo "Enabling i2c0 bus in $CONFIG"
-        echo "dtparam=i2c_vc=on" | sudo tee -a $CONFIG
-        newline
+        newline && echo "Enabling i2c0 bus in $CONFIG"
+        echo "dtparam=i2c_vc=on" | sudo tee -a $CONFIG && newline
     fi
 }
 
 usb_max_power() {
     if [ -e $CONFIG ] && grep -q "^max_usb_current=1$" $CONFIG; then
-        newline
-        echo "Max USB current setting already active"
+        newline && echo "Max USB current setting already active"
     else
-        newline
-        echo "Adjusting USB current setting in $CONFIG"
-        echo "max_usb_current=1" | sudo tee -a $CONFIG
-        newline
+        newline && echo "Adjusting USB current setting in $CONFIG"
+        echo "max_usb_current=1" | sudo tee -a $CONFIG && newline
     fi
 }
 
@@ -299,11 +291,10 @@ space_chk() {
             newline
             warning  "There is not enough space left to proceed with  installation"
             if confirm "Would you like to attempt to expand your filesystem?"; then
-                \curl -sS https://get.pimoroni.com/expandfs | sudo bash
+                \curl -sS $GETPOOL/expandfs | sudo bash
                 exit 1
             else
-                newline
-                exit 1
+                newline && exit 1
             fi
         fi
     fi
@@ -324,7 +315,7 @@ apt_pkg_req() {
 }
 
 apt_pkg_install() {
-    \curl -sS https://get.pimoroni.com/package | sudo bash -s - $1 || { warning "Apt failed to install $1!" && FAILED_PKG=true; }
+    \curl -sS $GETPOOL/package | sudo bash -s - $1 || { warning "Apt failed to install $1!" && FAILED_PKG=true; }
     newline
 }
 
@@ -405,7 +396,7 @@ else
     newline
     echo "If you want to see what this script does before"
     echo "running it, you should run:"
-    echo "\curl -sS https://get.pimoroni.com/$scriptname"
+    echo "\curl -sS $GETPOOL/$scriptname"
     newline
 fi
 
@@ -417,8 +408,7 @@ home_dir
 check_network
 
 if [ $debugmode != "no" ]; then
-    echo "USER_HOME is $USER_HOME"
-    newline
+    echo "USER_HOME is $USER_HOME" && newline
 fi
 
 if [ "$FORCE" != '-y' ]; then
@@ -441,15 +431,12 @@ fi
 if $IS_RASPBIAN && [ $raspbianonly == "yes" ]; then
     raspbian_check
     if [ $wheezysupport == "no" ] && $IS_WHEEZY || $IS_SQUEEZE; then
-        newline
-        warning "--- Warning ---"
-        newline
+        newline && warning "--- Warning ---" && newline
         echo "The $productname installer"
         echo "does not work on this version of Raspbian."
         echo "Check https://github.com/$gitusername/$gitreponame"
         echo "for additional information and support"
-        newline
-        exit 1
+        newline && exit 1
     fi
 fi
 
@@ -475,42 +462,30 @@ else
 fi
 
 if [ $i2creq == "yes" ]; then
-    echo "Note: $productname requires I2C communication"
-    newline
+    echo "Note: $productname requires I2C communication" && newline
 fi
 if [ $spireq == "yes" ]; then
-    echo "Note: $productname requires SPI communication"
-    newline
+    echo "Note: $productname requires SPI communication" && newline
 fi
 if [ $uartreq == "yes" ]; then
     echo "Note: $productname requires UART communication"
-    warning "The serial console will be disabled if you proceed!"
-    newline
+    warning "The serial console will be disabled if you proceed!" && newline
 fi
 
 if confirm "Do you wish to continue?"; then
+    sysupdate
 
 # hardware setup
 
-    newline
-    echo "Checking hardware requirements..."
+    newline && echo "Checking hardware requirements..."
 
-    if [ $uartreq == "yes" ]; then
-        newline
-        echo "The serial console must be disabled for $productname to work"
-        \curl -sS https://get.pimoroni.com/uarton | sudo bash -s - "-y"
-        ASK_TO_REBOOT=true
-        newline
-    fi
-
-    if [ $spireq == "yes" ]; then
-        newline
-        if ls /dev/spi* &> /dev/null; then
-            success "SPI already enabled"
-        else
-            echo "SPI must be enabled for $productname to work"
-            \curl -sS https://get.pimoroni.com/spi | sudo bash -s - "-y"
-            ASK_TO_REBOOT=true
+    if [ $gpioreq == "yes" ]; then
+        newline && echo "Checking for packages required for GPIO control..." && newline
+        if apt_pkg_req "python-rpi.gpio" && ! apt_pkg_install "python-rpi.gpio" &> /dev/null; then
+            pip2_chk && sudo $PIP2_BIN install RPi.GPIO -U
+        fi
+        if apt_pkg_req "python3-rpi.gpio" && ! apt_pkg_install "python3-rpi.gpio" &> /dev/null; then
+            pip3_chk && sudo $PIP3_BIN install RPi.GPIO -U
         fi
     fi
 
@@ -520,38 +495,58 @@ if confirm "Do you wish to continue?"; then
             success "I2C already enabled"
         else
             echo "I2C must be enabled for $productname to work"
-            \curl -sS https://get.pimoroni.com/i2c | sudo bash -s - "-y"
+            \curl -sS $GETPOOL/i2c | sudo bash -s - "-y"
             ASK_TO_REBOOT=true
         fi
-        newline
-        echo "Checking packages required by interface..."
-        newline
-        if apt_pkg_req "python-smbus" || apt_pkg_req "python3-smbus"; then
-            sysupdate
-            if apt_pkg_req "python-smbus"; then
-                if ! apt_pkg_install "python-smbus"  && python3 --version | grep "2.7" > /dev/null; then
-                    DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
-                    cd $DEBDIR
-                    wget $RASPOOL/main/i/i2c-tools/python-smbus_3.1.1+svn-2_armhf.deb &> /dev/null
-                    sudo dpkg -i $DEBDIR/python-smbus_3.1.1+svn-2_armhf.deb
-                fi
+        newline && echo "Checking packages required by I2C interface..." && newline
+        if apt_pkg_req "python-smbus"; then
+            if ! apt_pkg_install "python-smbus"  && python --version | grep "2.7" > /dev/null; then
+                DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
+                cd $DEBDIR
+                wget $RASPOOL/main/i/i2c-tools/python-smbus_3.1.1+svn-2_armhf.deb &> /dev/null
+                sudo dpkg -i $DEBDIR/python-smbus_3.1.1+svn-2_armhf.deb
             fi
-            if apt_pkg_req "python3-smbus"; then
-                if ! apt_pkg_install "python3-smbus" && python3 --version | grep "3.4" > /dev/null; then
+        fi
+        if apt_pkg_req "python3-smbus"; then
+            if ! apt_pkg_install "python3-smbus"; then
+                if python3 --version | grep "3.4" > /dev/null; then
                     DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
                     cd $DEBDIR
                     wget $RASPOOL/main/i/i2c-tools/python3-smbus_3.1.1+svn-2_armhf.deb &> /dev/null
                     sudo dpkg -i $DEBDIR/python3-smbus_3.1.1+svn-2_armhf.deb
+                elif python3 --version | grep "3.5" > /dev/null; then
+                    DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
+                    cd $DEBDIR
+                    wget $GETPOOL/python3-smbus1_1.1+35dbg-1_armhf.deb &> /dev/null
+                    sudo dpkg -i $DEBDIR/python3-smbus1_1.1+35dbg-1_armhf.deb
+                else
+                    warning "Unable to install compatible python3-smbus!"
                 fi
             fi
         fi
     fi
-    newline
+
+    if [ $spireq == "yes" ]; then
+        newline
+        if ls /dev/spi* &> /dev/null; then
+            success "SPI already enabled"
+        else
+            echo "SPI must be enabled for $productname to work"
+            \curl -sS $GETPOOL/spi | sudo bash -s - "-y"
+            ASK_TO_REBOOT=true
+        fi
+    fi
+
+    if [ $uartreq == "yes" ]; then
+        newline && echo "The serial console must be disabled for $productname to work"
+        \curl -sS $GETPOOL/uarton | sudo bash -s - "-y"
+        ASK_TO_REBOOT=true && newline
+    fi
 
 # minimum install routine
 
     if [ $gitrepoclone != "yes" ]; then
-
+        newline
         echo "$productname comes with examples and documentation that you may wish to install."
         echo "Performing a full install with ensure those resources are installed,"
         echo "along with all required dependencies. It may however take a while!"
@@ -580,11 +575,8 @@ if confirm "Do you wish to continue?"; then
     echo "Checking install requirements..."
 
     if command -v apt-get > /dev/null; then
-        newline
-        echo "Updating package indexes..."
-        sysupdate
-        newline
-        echo "Checking for dependencies..."
+        newline && echo "Updating package indexes..."
+        newline && echo "Checking for dependencies..."
 
         if $REMOVE_PKG; then
             for pkgrm in ${pkgaptremove[@]}; do
@@ -600,19 +592,6 @@ if confirm "Do you wish to continue?"; then
                 apt_pkg_install "$pkgdep"
             fi
         done
-        if raspbian_old; then
-            for pkgdep in ${pkgdeplist7[@]}; do
-                if apt_pkg_req "$pkgdep"; then
-                    apt_pkg_install "$pkgdep"
-                fi
-            done
-        else
-            for pkgdep in ${pkgdeplist8[@]}; do
-                if apt_pkg_req "$pkgdep"; then
-                    apt_pkg_install "$pkgdep"
-                fi
-            done
-        fi
         if [ $debpackage != "na" ]; then
             apt_pkg_install "$debpackage"
         fi
@@ -628,9 +607,7 @@ if confirm "Do you wish to continue?"; then
             fi
         done
         if [ $piplibname != "na" ] && [ $debpackage == "na" ]; then
-            newline
-            echo "Installing $productname library for Python 2..."
-            newline
+            newline && echo "Installing $productname library for Python 2..." && newline
             if ! sudo -H $PIP2_BIN install $piplibname -U; then
                 warning "Python 2 library install failed!"
                 echo "If problems persist, visit forums.pimoroni.com for support"
@@ -647,9 +624,7 @@ if confirm "Do you wish to continue?"; then
             fi
         done
         if [ $piplibname != "na" ] && [ $debpackage == "na" ]; then
-            newline
-            echo "Installing $productname library for Python 3..."
-            newline
+            newline && echo "Installing $productname library for Python 3..." && newline
                 if ! sudo -H $PIP3_BIN install $piplibname -U; then
                     warning "Python 3 library install failed!"
                 echo "If problems persist, visit forums.pimoroni.com for support"
@@ -671,13 +646,10 @@ if confirm "Do you wish to continue?"; then
             rm -Rf $installdir/$gitclonedir
         fi
         if [ -d $installdir/$gitclonedir ]; then
-            newline
-            echo "Github repo already present. Updating..."
-            cd $installdir/$gitclonedir
-            git pull
+            newline && echo "Github repo already present. Updating..."
+            cd $installdir/$gitclonedir && git pull
         else
-            newline
-            echo "Cloning Github repo locally..."
+            newline && echo "Cloning Github repo locally..."
             cd $installdir
             if [ $debugmode != "no" ]; then
                 echo "git user name is $gitusername"
@@ -692,9 +664,7 @@ if confirm "Do you wish to continue?"; then
     fi
 
     if [ $repoinstall == "yes" ]; then
-        newline
-        echo "Installing library..."
-        newline
+        newline && echo "Installing library..." && newline
         cd $installdir/$gitreponame/$libdir
         if [ $pip2support == "yes" ] && [ -n $(which python2) ]; then
             sudo python2 ./setup.py install
@@ -708,9 +678,7 @@ if confirm "Do you wish to continue?"; then
 # additional install
 
     if ! $MIN_INSTALL; then
-        newline
-        echo "Checking for additional software..."
-
+        newline && echo "Checking for additional software..."
         moredepreq=false
 
         for moredep in ${moreaptdep[@]}; do
@@ -756,9 +724,7 @@ if confirm "Do you wish to continue?"; then
         if ! command -v git > /dev/null; then
             apt_pkg_install git
         fi
-        newline
-        echo "Downloading examples and documentation..."
-        newline
+        newline && echo "Downloading examples and documentation..." && newline
         TMPDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
         cd $TMPDIR
         git clone --depth=1 https://github.com/$gitusername/$gitreponame
@@ -787,9 +753,7 @@ if confirm "Do you wish to continue?"; then
                 fi
             fi
         done
-        newline
-        success "Resources for your $productname were copied to"
-        echo  "$installdir/"
+        newline && success "Resources for your $productname were copied to $installdir"
         rm -rf $TMPDIR
     fi
 
@@ -797,20 +761,13 @@ if confirm "Do you wish to continue?"; then
 
     if [ $customcmd == "no" ]; then
         if [ -n "$pkgaptremove" ]; then
-            newline
-            echo "Finalising Install..."
-            newline
-            sysclean
-            newline
+            newline && echo "Finalising Install..." && newline
+            sysclean && newline
         fi
-        newline
-        success "All done!"
-        newline
-        echo "Enjoy your $productname!"
-        newline
+        newline && success "All done!" && newline
+        echo "Enjoy your $productname!" && newline
     else # custom block starts here
-        newline
-        echo "Finalising Install..."
+        newline && echo "Finalising Install..."
         # place all custom commands in this scope
         newline
     fi
@@ -821,13 +778,10 @@ if confirm "Do you wish to continue?"; then
     fi
 
     if [ $promptreboot == "yes" ] || $ASK_TO_REBOOT; then
-        sysreboot
-        newline
+        sysreboot && newline
     fi
 else
-    newline
-    echo "Aborting..."
-    newline
+    newline && echo "Aborting..." && newline
 fi
 
 exit 0
diff --git a/installers/template b/installers/template
--- a/installers/template
+++ b/installers/template
@@ -66,13 +66,11 @@ pkgaptremove=() # list of conflicting apt packages to remove
 pkgdeplist1=( "i2c-tools" ) # list core dependencies
 pkgdeplist2=( "python-pip" ) # list python 2 dependencies
 pkgdeplist3=( "python3-pip" ) # list python 3 dependencies
-pkgdeplist7=() # list dependencies for Wheezy only
-pkgdeplist8=() # list dependencies for Jessie only
 moreaptdep=( "git" ) # list of all the additional apt dependencies
 morepipdep=() # list of all the additional pip dependencies
 spacereq=150 # minimum size required on root partition in MB
 
-# template 1609161145
+# template 1609161340
 
 FORCE=$1
 ASK_TO_REBOOT=false
@@ -89,8 +87,9 @@ INITABCONF=/etc/inittab
 BLACKLIST=/etc/modprobe.d/raspi-blacklist.conf
 LOADMOD=/etc/modules
 
-RASPOOL="http://mirrordirector.raspbian.org/raspbian/pool"
 DEBPOOL="http://ftp.debian.org/debian/pool"
+GETPOOL="https://get.pimoroni.com/"
+RASPOOL="http://mirrordirector.raspbian.org/raspbian/pool"
 
 # function define
 
@@ -292,7 +291,7 @@ space_chk() {
             newline
             warning  "There is not enough space left to proceed with  installation"
             if confirm "Would you like to attempt to expand your filesystem?"; then
-                \curl -sS https://get.pimoroni.com/expandfs | sudo bash
+                \curl -sS $GETPOOL/expandfs | sudo bash
                 exit 1
             else
                 newline && exit 1
@@ -316,7 +315,7 @@ apt_pkg_req() {
 }
 
 apt_pkg_install() {
-    \curl -sS https://get.pimoroni.com/package | sudo bash -s - $1 || { warning "Apt failed to install $1!" && FAILED_PKG=true; }
+    \curl -sS $GETPOOL/package | sudo bash -s - $1 || { warning "Apt failed to install $1!" && FAILED_PKG=true; }
     newline
 }
 
@@ -397,7 +396,7 @@ else
     newline
     echo "If you want to see what this script does before"
     echo "running it, you should run:"
-    echo "\curl -sS https://get.pimoroni.com/$scriptname"
+    echo "\curl -sS $GETPOOL/$scriptname"
     newline
 fi
 
@@ -474,25 +473,19 @@ if [ $uartreq == "yes" ]; then
 fi
 
 if confirm "Do you wish to continue?"; then
+    sysupdate
 
 # hardware setup
 
     newline && echo "Checking hardware requirements..."
 
-    if [ $uartreq == "yes" ]; then
-        newline && echo "The serial console must be disabled for $productname to work"
-        \curl -sS https://get.pimoroni.com/uarton | sudo bash -s - "-y"
-        ASK_TO_REBOOT=true && newline
-    fi
-
-    if [ $spireq == "yes" ]; then
-        newline
-        if ls /dev/spi* &> /dev/null; then
-            success "SPI already enabled"
-        else
-            echo "SPI must be enabled for $productname to work"
-            \curl -sS https://get.pimoroni.com/spi | sudo bash -s - "-y"
-            ASK_TO_REBOOT=true
+    if [ $gpioreq == "yes" ]; then
+        newline && echo "Checking for packages required for GPIO control..." && newline
+        if apt_pkg_req "python-rpi.gpio" && ! apt_pkg_install "python-rpi.gpio" &> /dev/null; then
+            pip2_chk && sudo $PIP2_BIN install RPi.GPIO -U
+        fi
+        if apt_pkg_req "python3-rpi.gpio" && ! apt_pkg_install "python3-rpi.gpio" &> /dev/null; then
+            pip3_chk && sudo $PIP3_BIN install RPi.GPIO -U
         fi
     fi
 
@@ -502,29 +495,52 @@ if confirm "Do you wish to continue?"; then
             success "I2C already enabled"
         else
             echo "I2C must be enabled for $productname to work"
-            \curl -sS https://get.pimoroni.com/i2c | sudo bash -s - "-y"
+            \curl -sS $GETPOOL/i2c | sudo bash -s - "-y"
             ASK_TO_REBOOT=true
         fi
-        newline && echo "Checking packages required by interface..." && newline
-        if apt_pkg_req "python-smbus" || apt_pkg_req "python3-smbus"; then
-            sysupdate
-            if apt_pkg_req "python-smbus"; then
-                if ! apt_pkg_install "python-smbus"  && python3 --version | grep "2.7" > /dev/null; then
-                    DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
-                    cd $DEBDIR
-                    wget $RASPOOL/main/i/i2c-tools/python-smbus_3.1.1+svn-2_armhf.deb &> /dev/null
-                    sudo dpkg -i $DEBDIR/python-smbus_3.1.1+svn-2_armhf.deb
-                fi
+        newline && echo "Checking packages required by I2C interface..." && newline
+        if apt_pkg_req "python-smbus"; then
+            if ! apt_pkg_install "python-smbus"  && python --version | grep "2.7" > /dev/null; then
+                DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
+                cd $DEBDIR
+                wget $RASPOOL/main/i/i2c-tools/python-smbus_3.1.1+svn-2_armhf.deb &> /dev/null
+                sudo dpkg -i $DEBDIR/python-smbus_3.1.1+svn-2_armhf.deb
             fi
-            if apt_pkg_req "python3-smbus"; then
-                if ! apt_pkg_install "python3-smbus" && python3 --version | grep "3.4" > /dev/null; then
+        fi
+        if apt_pkg_req "python3-smbus"; then
+            if ! apt_pkg_install "python3-smbus"; then
+                if python3 --version | grep "3.4" > /dev/null; then
                     DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
                     cd $DEBDIR
                     wget $RASPOOL/main/i/i2c-tools/python3-smbus_3.1.1+svn-2_armhf.deb &> /dev/null
                     sudo dpkg -i $DEBDIR/python3-smbus_3.1.1+svn-2_armhf.deb
+                elif python3 --version | grep "3.5" > /dev/null; then
+                    DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
+                    cd $DEBDIR
+                    wget $GETPOOL/python3-smbus1_1.1+35dbg-1_armhf.deb &> /dev/null
+                    sudo dpkg -i $DEBDIR/python3-smbus1_1.1+35dbg-1_armhf.deb
+                else
+                    warning "Unable to install compatible python3-smbus!"
                 fi
             fi
         fi
+    fi
+
+    if [ $spireq == "yes" ]; then
+        newline
+        if ls /dev/spi* &> /dev/null; then
+            success "SPI already enabled"
+        else
+            echo "SPI must be enabled for $productname to work"
+            \curl -sS $GETPOOL/spi | sudo bash -s - "-y"
+            ASK_TO_REBOOT=true
+        fi
+    fi
+
+    if [ $uartreq == "yes" ]; then
+        newline && echo "The serial console must be disabled for $productname to work"
+        \curl -sS $GETPOOL/uarton | sudo bash -s - "-y"
+        ASK_TO_REBOOT=true && newline
     fi
 
 # minimum install routine
@@ -560,7 +576,6 @@ if confirm "Do you wish to continue?"; then
 
     if command -v apt-get > /dev/null; then
         newline && echo "Updating package indexes..."
-        sysupdate
         newline && echo "Checking for dependencies..."
 
         if $REMOVE_PKG; then
@@ -577,19 +592,6 @@ if confirm "Do you wish to continue?"; then
                 apt_pkg_install "$pkgdep"
             fi
         done
-        if raspbian_old; then
-            for pkgdep in ${pkgdeplist7[@]}; do
-                if apt_pkg_req "$pkgdep"; then
-                    apt_pkg_install "$pkgdep"
-                fi
-            done
-        else
-            for pkgdep in ${pkgdeplist8[@]}; do
-                if apt_pkg_req "$pkgdep"; then
-                    apt_pkg_install "$pkgdep"
-                fi
-            done
-        fi
         if [ $debpackage != "na" ]; then
             apt_pkg_install "$debpackage"
         fi
