all based on multi os-releases template

diff --git a/installers/bluetooth b/installers/bluetooth
--- a/installers/bluetooth
+++ b/installers/bluetooth
@@ -71,7 +71,7 @@ moreaptdep=() # list of additional apt dependencies
 pipdeplist=() # list of dependencies to source from pip
 morepipdep=() # list of additional pip dependencies
 
-# template 1609082150
+# template 1609170000
 
 FORCE=$1
 ASK_TO_REBOOT=false
@@ -88,8 +88,9 @@ INITABCONF=/etc/inittab
 BLACKLIST=/etc/modprobe.d/raspi-blacklist.conf
 LOADMOD=/etc/modules
 
-RASPOOL="http://mirrordirector.raspbian.org/raspbian/pool"
 DEBPOOL="http://ftp.debian.org/debian/pool"
+GETPOOL="https://get.pimoroni.com"
+RASPOOL="http://mirrordirector.raspbian.org/raspbian/pool"
 
 # function define
 
@@ -177,7 +178,8 @@ os_check() {
     IS_RASPBIAN=false
     IS_MACOSX=false
     IS_SUPPORTED=false
-
+    IS_EXPERIMENTAL=false
+    
     if [ -f /etc/os-release ]; then
         if cat /etc/os-release | grep "Raspbian" > /dev/null; then
             IS_RASPBIAN=true && IS_SUPPORTED=true
@@ -186,6 +188,11 @@ os_check() {
             for os in ${osreleases[@]}; do
                 if cat /etc/os-release | grep "$os" > /dev/null; then
                     IS_SUPPORTED=true
+                fi
+            done
+            for os in ${oswarning[@]}; do
+                if cat /etc/os-release | grep "$os" > /dev/null; then
+                    IS_EXPERIMENTAL=true
                 fi
             done
         fi
@@ -251,12 +258,6 @@ servd_trig() {
     fi
 }
 
-servd_trig() {
-    if command -v service > /dev/null; then
-        sudo service $1 $2
-    fi
-}
-
 get_init_sys() {
     if command -v systemctl > /dev/null && systemctl | grep -q '\-\.mount'; then
         SYSTEMD=1
@@ -291,7 +292,7 @@ space_chk() {
             newline
             warning  "There is not enough space left to proceed with  installation"
             if confirm "Would you like to attempt to expand your filesystem?"; then
-                \curl -sS https://get.pimoroni.com/expandfs | sudo bash
+                \curl -sS $GETPOOL/expandfs | sudo bash
                 exit 1
             else
                 newline && exit 1
@@ -315,7 +316,7 @@ apt_pkg_req() {
 }
 
 apt_pkg_install() {
-    \curl -sS https://get.pimoroni.com/package | sudo bash -s - $1 || { warning "Apt failed to install $1!" && FAILED_PKG=true; }
+    \curl -sS $GETPOOL/package | sudo bash -s - $1 || { warning "Apt failed to install $1!" && FAILED_PKG=true && return 1; }
     newline
 }
 
@@ -396,7 +397,7 @@ else
     newline
     echo "If you want to see what this script does before"
     echo "running it, you should run:"
-    echo "\curl -sS https://get.pimoroni.com/$scriptname"
+    echo "\curl -sS $GETPOOL/$scriptname"
     newline
 fi
 
@@ -405,14 +406,10 @@ fi
 arch_check
 os_check
 home_dir
-check_network
+space_chk
 
 if [ $debugmode != "no" ]; then
     echo "USER_HOME is $USER_HOME" && newline
-fi
-
-if [ "$FORCE" != '-y' ]; then
-    space_chk
 fi
 
 if ! $IS_ARMHF; then
@@ -420,22 +417,22 @@ if ! $IS_ARMHF; then
     newline && exit 1
 fi
 
-if ! $IS_RASPBIAN && [ $raspbianonly == "yes" ]; then
-    warning "Your operating system is not supported, sorry!"
-    newline && exit 1
-elif ! $IS_SUPPORTED; then
-    warning "Your operating system is not supported, sorry!"
-    newline && exit 1
-fi
-
-if $IS_RASPBIAN && [ $raspbianonly == "yes" ]; then
+if $IS_RASPBIAN; then
     raspbian_check
-    if [ $wheezysupport == "no" ] && $IS_WHEEZY || $IS_SQUEEZE; then
+    if [ $wheezysupport == "no" ] && raspbian_old; then
         newline && warning "--- Warning ---" && newline
         echo "The $productname installer"
         echo "does not work on this version of Raspbian."
         echo "Check https://github.com/$gitusername/$gitreponame"
         echo "for additional information and support"
+        newline && exit 1
+    fi
+elif [ $raspbianonly == "yes" ];then
+        warning "This script is intended for Raspbian on a Raspberry Pi!"
+        newline && exit 1
+else
+    if ! $IS_SUPPORTED && ! $IS_EXPERIMENTAL; then
+        warning "Your operating system is not supported, sorry!"
         newline && exit 1
     fi
 fi
@@ -474,14 +471,35 @@ fi
 
 if confirm "Do you wish to continue?"; then
 
+# basic environment preparation
+
+    newline && echo "Checking environment..."
+    check_network
+    sysupdate
+    if ! command -v curl > /dev/null; then
+        apt_pkg_install "curl"
+    fi
+    if ! command -v wget > /dev/null; then
+        apt_pkg_install "wget"
+    fi
+    if ! command -v pip > /dev/null; then
+        apt_pkg_install "python-pip"
+        apt_pkg_install "python3-pip"
+    fi
+    pip2_chk && pip3_chk
+
 # hardware setup
 
     newline && echo "Checking hardware requirements..."
 
-    if [ $uartreq == "yes" ]; then
-        newline && echo "The serial console must be disabled for $productname to work"
-        \curl -sS https://get.pimoroni.com/uarton | sudo bash -s - "-y"
-        ASK_TO_REBOOT=true && newline
+    if [ $gpioreq == "yes" ]; then
+        newline && echo "Checking for packages required for GPIO control..." && newline
+        if apt_pkg_req "python-rpi.gpio" && ! apt_pkg_install "python-rpi.gpio" &> /dev/null; then
+            sudo $PIP2_BIN install RPi.GPIO -U && FAILED_PKG=false
+        fi
+        if apt_pkg_req "python3-rpi.gpio" && ! apt_pkg_install "python3-rpi.gpio" &> /dev/null; then
+            sudo $PIP3_BIN install RPi.GPIO -U && FAILED_PKG=false
+        fi
     fi
 
     if [ $spireq == "yes" ]; then
@@ -490,8 +508,15 @@ if confirm "Do you wish to continue?"; then
             success "SPI already enabled"
         else
             echo "SPI must be enabled for $productname to work"
-            \curl -sS https://get.pimoroni.com/spi | sudo bash -s - "-y"
+            \curl -sS $GETPOOL/spi | sudo bash -s - "-y"
             ASK_TO_REBOOT=true
+        fi
+        newline && echo "Checking packages required by SPI interface..." && newline
+        if apt_pkg_req "python-spidev" && ! apt_pkg_install "python-spidev" &> /dev/null; then
+            sudo $PIP2_BIN install spidev -U && FAILED_PKG=false
+        fi
+        if apt_pkg_req "python3-spidev" && ! apt_pkg_install "python3-spidev" &> /dev/null; then
+            sudo $PIP3_BIN install spidev -U && FAILED_PKG=false
         fi
     fi
 
@@ -501,29 +526,51 @@ if confirm "Do you wish to continue?"; then
             success "I2C already enabled"
         else
             echo "I2C must be enabled for $productname to work"
-            \curl -sS https://get.pimoroni.com/i2c | sudo bash -s - "-y"
+            \curl -sS $GETPOOL/i2c | sudo bash -s - "-y"
             ASK_TO_REBOOT=true
         fi
-        newline && echo "Checking packages required by interface..." && newline
-        if apt_pkg_req "python-smbus" || apt_pkg_req "python3-smbus"; then
-            sysupdate
-            if apt_pkg_req "python-smbus"; then
-                if ! apt_pkg_install "python-smbus"  && python3 --version | grep "2.7" > /dev/null; then
-                    DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
-                    cd $DEBDIR
-                    wget $RASPOOL/main/i/i2c-tools/python-smbus_3.1.1+svn-2_armhf.deb &> /dev/null
-                    sudo dpkg -i $DEBDIR/python-smbus_3.1.1+svn-2_armhf.deb
-                fi
+        newline && echo "Checking packages required by I2C interface..." && newline
+        if apt_pkg_req "python-smbus"; then
+            if ! apt_pkg_install "python-smbus" && python --version | grep "2.7" > /dev/null; then
+                echo "python-smbus can't be found, fetching from alternative location..."
+                FAILED_PKG=false
+                DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX` && cd $DEBDIR
+                wget $RASPOOL/main/i/i2c-tools/python-smbus_3.1.1+svn-2_armhf.deb &> /dev/null
+                sudo dpkg -i $DEBDIR/python-smbus_3.1.1+svn-2_armhf.deb
             fi
-            if apt_pkg_req "python3-smbus"; then
-                if ! apt_pkg_install "python3-smbus" && python3 --version | grep "3.4" > /dev/null; then
-                    DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
-                    cd $DEBDIR
+        fi
+        if ! $PIP2_BIN list | grep "smbus" > /dev/null; then
+            FAILED_PKG=true
+        fi
+        if apt_pkg_req "python3-smbus"; then
+            if ! apt_pkg_install "python3-smbus"; then
+                if python3 --version | grep "3.4" > /dev/null; then
+                    echo "python3-smbus can't be found, fetching from alternative location..."
+                    FAILED_PKG=false
+                    DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX` && cd $DEBDIR
                     wget $RASPOOL/main/i/i2c-tools/python3-smbus_3.1.1+svn-2_armhf.deb &> /dev/null
                     sudo dpkg -i $DEBDIR/python3-smbus_3.1.1+svn-2_armhf.deb
+                elif python3 --version | grep "3.5" > /dev/null; then
+                    echo "python3-smbus can't be found, fetching from alternative location..."
+                    FAILED_PKG=false
+                    DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX` && cd $DEBDIR
+                    wget $GETPOOL/python3-smbus1_1.1+35dbg-1_armhf.deb &> /dev/null
+                    sudo dpkg -i $DEBDIR/python3-smbus1_1.1+35dbg-1_armhf.deb
+                else
+                    warning "Unable to install compatible python3-smbus!"
+                    FAILED_PKG=true
                 fi
             fi
         fi
+        if ! $PIP3_BIN list | grep "smbus" > /dev/null; then
+            FAILED_PKG=true
+        fi
+    fi
+
+    if [ $uartreq == "yes" ]; then
+        newline && echo "The serial console must be disabled for $productname to work"
+        \curl -sS $GETPOOL/uarton | sudo bash -s - "-y"
+        ASK_TO_REBOOT=true && newline
     fi
 
 # minimum install routine
@@ -531,7 +578,7 @@ if confirm "Do you wish to continue?"; then
     if [ $gitrepoclone != "yes" ]; then
         newline
         echo "$productname comes with examples and documentation that you may wish to install."
-        echo "Performing a full install with ensure those resources are installed,"
+        echo "Performing a full install will ensure those resources are installed,"
         echo "along with all required dependencies. It may however take a while!"
         newline
 
@@ -557,34 +604,30 @@ if confirm "Do you wish to continue?"; then
 
     echo "Checking install requirements..."
 
-    if command -v apt-get > /dev/null; then
-        newline && echo "Updating package indexes..."
-        sysupdate
-        newline && echo "Checking for dependencies..."
+    newline && echo "Updating package indexes..."
+    newline && echo "Checking for dependencies..."
 
-        if $REMOVE_PKG; then
-            for pkgrm in ${pkgaptremove[@]}; do
-                warning "Installed package conflicts with requirements"
-                sudo apt-get remove "$pkgrm"
-            done
-        fi
-
-        pkgdeplist=( "${pkgdeplist1[@]}" "${pkgdeplist2[@]}" "${pkgdeplist3[@]}" )
-
-        for pkgdep in ${pkgdeplist[@]}; do
-            if apt_pkg_req "$pkgdep"; then
-                apt_pkg_install "$pkgdep"
-            fi
+    if $REMOVE_PKG; then
+        for pkgrm in ${pkgaptremove[@]}; do
+            warning "Installed package conflicts with requirements"
+            sudo apt-get remove "$pkgrm"
         done
-        if [ $debpackage != "na" ]; then
-            apt_pkg_install "$debpackage"
+    fi
+
+    pkgdeplist=( "${pkgdeplist1[@]}" "${pkgdeplist2[@]}" "${pkgdeplist3[@]}" )
+
+    for pkgdep in ${pkgdeplist[@]}; do
+        if apt_pkg_req "$pkgdep"; then
+            apt_pkg_install "$pkgdep"
         fi
+    done
+    if [ $debpackage != "na" ]; then
+        apt_pkg_install "$debpackage"
     fi
 
 # pypi repo install
 
     if [ $pip2support == "yes" ] && [ -n $(which python2) ]; then
-        pip2_chk
         for pipdep in ${pipdeplist[@]}; do
             if pip2_pkg_req "$pipdep"; then
                 sudo -H $PIP2_BIN install "$pipdep"
@@ -601,7 +644,6 @@ if confirm "Do you wish to continue?"; then
     fi
 
     if [ $pip3support == "yes" ] && [ -n $(which python3) ]; then
-        pip3_chk
         for pipdep in ${pipdeplist[@]}; do
             if pip3_pkg_req "$pipdep"; then
                 sudo -H $PIP3_BIN install "$pipdep"
@@ -771,6 +813,11 @@ if confirm "Do you wish to continue?"; then
 
     if $FAILED_PKG; then
         warning "Some packages could not be installed, review the output for details!"
+        newline
+    fi
+    if $IS_EXPERIMENTAL; then
+        warning "Support for your operating system is experimental. Please visit"
+        warning "forums.pimoroni.com if you experience issues with this product."
         newline
     fi
 
