Finalised with minimal routine and nested resources

diff --git a/installers/botlab b/installers/botlab
--- a/installers/botlab
+++ b/installers/botlab
@@ -64,13 +64,13 @@ moreaptdep=() # list of all the additional apt dependencies
 morepipdep=() # list of all the additional pip dependencies
 spacereq=150 # minimum size required on root partition in MB
 
-# template 1607282205
+# template 1607292320
 
 FORCE=$1
 DEVICE_TREE=true
 ASK_TO_REBOOT=false
-UPDATE_DB=false
 CURRENT_SETTING=false
+MIN_INSTALL=false
 REMOVE_PKG=false
 
 BOOTCMD=/boot/cmdline.txt
@@ -96,6 +96,15 @@ confirm() {
             false
         fi
     fi
+}
+
+prompt() {
+        read -r -p "$1 [y/N] " response < /dev/tty
+        if [[ $response =~ ^(yes|y|Y)$ ]]; then
+            true
+        else
+            false
+        fi
 }
 
 success() {
@@ -136,7 +145,7 @@ sysreboot() {
     warning "Some changes made to your system require"
     warning "your computer to reboot to take effect."
     newline
-    if confirm "Would you like to reboot now?"; then
+    if prompt "Would you like to reboot now?"; then
         sync
         sudo reboot
     fi
@@ -346,7 +355,7 @@ MAINSTART
 
 newline
 echo "This script will install everything needed to use"
-echo "$productname"
+echo "the $topdir $productname"
 newline
 warning "--- Warning ---"
 newline
@@ -370,14 +379,6 @@ if [ "$FORCE" != '-y' ]; then
     space_chk
 fi
 
-if [ $localdir != "na" ]; then 
-    WORKING_DIR="$USER_HOME/$topdir/$localdir"
-else
-    WORKING_DIR="$USER_HOME/$topdir"
-fi
-
-[ -d $WORKING_DIR ] || mkdir -p $WORKING_DIR
-
 if $IS_RASPBIAN; then
     raspbian_check
     if [ $squeezesupport == "no" ] && $IS_SQUEEZE; then
@@ -390,8 +391,7 @@ if $IS_RASPBIAN; then
         echo "for additional information and support"
         newline
         exit 1
-    fi
-    if [ $wheezysupport == "no" ] && $IS_WHEEZY; then
+    elif [ $wheezysupport == "no" ] && $IS_WHEEZY; then
         newline
         warning "--- Warning ---"
         newline
@@ -465,7 +465,7 @@ if confirm "Do you wish to continue?"; then
     if [ $spireq == "yes" ]; then
         newline
         if ls /dev/spi* &> /dev/null; then
-            success "SPI Already enabled"
+            success "SPI already enabled"
         else
             echo "SPI must be enabled for $productname to work"
             \curl -sS https://get.pimoroni.com/spi | sudo bash -s - "-y"
@@ -476,7 +476,7 @@ if confirm "Do you wish to continue?"; then
     if [ $i2creq == "yes" ]; then
         newline
         if ls /dev/i2c* &> /dev/null; then
-            success "I2C Already enabled"
+            success "I2C already enabled"
         else
             echo "I2C must be enabled for $productname to work"
             \curl -sS https://get.pimoroni.com/i2c | sudo bash -s - "-y"
@@ -486,97 +486,71 @@ if confirm "Do you wish to continue?"; then
     success "Done!"
     newline
 
+# minimum install routine
+
+    if [ $gitrepoclone != "yes" ]; then
+            
+        echo "$productname includes a number of examples that you may wish to install."
+        echo "Performing a full install with ensure those examples are installed,"
+        echo "along with all required dependencies. It may however take a while!"
+        newline
+
+        if ! confirm "Do you wish to perform a full install?"; then
+            MIN_INSTALL=true
+        fi
+    fi
+
+    if ! $MIN_INSTALL;then
+        if [ $localdir != "na" ]; then 
+            WORKING_DIR="$USER_HOME/$topdir/$localdir"
+        else
+            WORKING_DIR="$USER_HOME/$topdir"
+        fi
+        [ -d $WORKING_DIR ] || mkdir -p $WORKING_DIR
+    fi
+
 # raspbian repo install
 
     echo "Checking install requirements..."
 
     if command -v apt-get > /dev/null; then
+        newline
+        echo "Updating package indexes..."
+        sysupdate
+        newline
+        echo "Checking for dependencies..."
 
-        for pkgrm in ${pkgaptremove[@]}; do
-            if apt_pkg_req "$pkgrm"; then
-                REMOVE_PKG=true
-            fi
-        done
-        if [ $debpackage != "na" ]; then
-            UPDATE_DB=true
+        if $REMOVE_PKG; then
+            for pkgrm in ${pkgaptremove[@]}; do
+                warning "Installed package conflicts with requirements"
+                sudo apt-get remove "$pkgrm"
+            done
         fi
-        for pkgdep in ${pkgdeplist1[@]}; do
-            if apt_pkg_req "$pkgdep"; then
-                UPDATE_DB=true
-            fi
-        done
-        for pkgdep in ${pkgdeplist2[@]}; do
-            if apt_pkg_req "$pkgdep"; then
-                UPDATE_DB=true
-            fi
-        done
-        for pkgdep in ${pkgdeplist3[@]}; do
-            if apt_pkg_req "$pkgdep"; then
-                UPDATE_DB=true
-            fi
-        done
-        for pkgdep in ${pkgdeplist7[@]}; do
-            if apt_pkg_req "$pkgdep"; then
-                UPDATE_DB=true
-            fi
-        done
-        for pkgdep in ${pkgdeplist8[@]}; do
-            if apt_pkg_req "$pkgdep"; then
-                UPDATE_DB=true
-            fi
-        done
-        for morepkgdep in ${moreaptdep[@]}; do
-            if apt_pkg_req "$morepkgdep"; then
-                UPDATE_DB=true
-            fi
-        done
 
-        if $UPDATE_DB; then
-            newline
-            echo "Updating package indexes..."
-            sysupdate
-            newline
-            echo "Checking for dependencies..."
+        pkgdeplist=( "${pkgdeplist1[@]}" "${pkgdeplist2[@]}" "${pkgdeplist3[@]}" )
 
-            if $REMOVE_PKG; then
-                for pkgrm in ${pkgaptremove[@]}; do
-                    warning "Installed package conflicts with requirements"
-                    sudo apt-get remove "$pkgrm"
-                done
+        for pkgdep in ${pkgdeplist[@]}; do
+            if apt_pkg_req "$pkgdep"; then
+                apt_pkg_install "$pkgdep"
             fi
-            for pkgdep in ${pkgdeplist1[@]}; do
-                if apt_pkg_req "$pkgdep"; then
-                    apt_pkg_install "$pkgdep"
-                fi
-            done
-            for pkgdep in ${pkgdeplist2[@]}; do
-                if apt_pkg_req "$pkgdep"; then
-                    apt_pkg_install "$pkgdep"
-                fi
-            done
-            for pkgdep in ${pkgdeplist3[@]}; do
-                if apt_pkg_req "$pkgdep"; then
-                    apt_pkg_install "$pkgdep"
-                fi
-            done
+        done
+        if raspbian_old; then 
             for pkgdep in ${pkgdeplist7[@]}; do
                 if apt_pkg_req "$pkgdep"; then
                     apt_pkg_install "$pkgdep"
                 fi
             done
-            if ! raspbian_old; then
-                for pkgdep in ${pkgdeplist8[@]}; do
-                    if apt_pkg_req "$pkgdep"; then
-                        apt_pkg_install "$pkgdep"
-                    fi
-                done
-            fi
-            if [ $debpackage != "na" ]; then
-                apt_pkg_install "$debpackage"
-            fi
         else
-            success "Done!"
+            for pkgdep in ${pkgdeplist8[@]}; do
+                if apt_pkg_req "$pkgdep"; then
+                    apt_pkg_install "$pkgdep"
+                fi
+            done
         fi
+        if [ $debpackage != "na" ]; then
+            apt_pkg_install "$debpackage"
+        fi
+        success "Done!"
     fi
 
 # pypi repo install
@@ -598,55 +572,25 @@ if confirm "Do you wish to continue?"; then
         if [ $pip2support == "yes" ] && [ -n $(which python2) ]; then
             if command -v pip > /dev/null; then
                 newline
-                echo "Checking for Python 2 library..."
-
-                if pip_pkg_req "$piplibname"; then
-                    echo "Installing $productname library for Python 2..."
-                    newline
-                    if ! sudo pip install $piplibname; then
-                        warning "Python 2 library install failed!"
-                        echo "If problems persist, visit forums.pimoroni.com for support"
-                        exit 1
-                    fi
-                    success "Done!"
-                else
-                    success "Found!"
-                    newline
-                    if confirm "Python 2 module found. Reinstall/Update?"; then
-                        if ! sudo pip install $piplibname -I; then
-                            warning "Python 2 library install failed!"
-                            echo "If problems persist, visit forums.pimoroni.com for support"
-                            exit 1
-                        fi
-                        success "Done!"
-                    fi
+                echo "Installing $productname library for Python 2..."
+                newline
+                if ! sudo pip install $piplibname -I; then
+                    warning "Python 2 library install failed!"
+                    echo "If problems persist, visit forums.pimoroni.com for support"
+                    exit 1
                 fi
+                success "Done!"
             fi
         fi
-
         if [ $pip3support == "yes" ] && [ -n $(which python3) ]; then
             if [ -n "$PIP3_BIN" ]; then
                 newline
-                echo "Checking for Python 3 library..."
-                if pip_pkg_req3 "$piplibname"; then
-                    echo "Installing $productname library for Python 3..."
-                    newline
-                    if ! sudo $PIP3_BIN install $piplibname; then
+                echo "Installing $productname library for Python 3..."
+                newline
+                    if ! sudo $PIP3_BIN install $piplibname -I; then
                         warning "Python 3 library install failed!"
-                        echo "If problems persist, visit forums.pimoroni.com for support"
-                        exit 1
-                    fi
-                else
-                    success "Found!"
-                    newline
-                    if confirm "Python 3 module found. Reinstall/Update?"; then
-                        if ! sudo $PIP3_BIN install $piplibname -I; then
-                            warning "Python 3 library install failed!"
-                            echo "If problems persist, visit forums.pimoroni.com for support"
-                            exit 1
-                        fi
-                        success "Done!"
-                    fi
+                    echo "If problems persist, visit forums.pimoroni.com for support"
+                    exit 1
                 fi
             fi
         fi
@@ -695,73 +639,94 @@ if confirm "Do you wish to continue?"; then
 
 # resources install
 
-    if [ -n "$copydir" ]; then
+    if ! $MIN_INSTALL && [ -n "$copydir" ]; then
+        newline
         echo "Downloading examples and documentation..."
+        newline
         TMPDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
         cd $TMPDIR
         git clone --depth=1 https://github.com/$gitusername/$gitreponame
         cd $WORKING_DIR
         for repodir in ${copydir[@]}; do
             if [ -d $repodir ] && [ $repodir != "documentation" ]; then
-                if confirm "Resources already exist, shall I replace them?"; then
-                    mv $WORKING_DIR $WORKING_DIR-backup
-                    cp -R $TMPDIR/$gitreponame/$repodir $WORKING_DIR/$repodir
-                    warning "I backed up the examples to $WORKING_DIR-backup, just in case you've changed anything!"
-                else
-                    cp -R $TMPDIR/$gitreponame/$repodir $WORKING_DIR/$repodir                    
+                newline
+                if [ -d $WORKING_DIR/$repodir-backup ]; then
+                    rm -R $WORKING_DIR/$repodir-old &> /dev/null
+                    mv $WORKING_DIR/$repodir-backup $WORKING_DIR/$repodir-old &> /dev/null
                 fi
-                success "Resources copied to $WORKING_DIR/"
-                rm -rf $TMPDIR
+                mv $WORKING_DIR/$repodir $WORKING_DIR/$repodir-backup &> /dev/null
+                if [ $gitrepotop != "root" ]; then
+                    cp -R $TMPDIR/$gitreponame/$gitrepotop/$repodir $WORKING_DIR/$repodir &> /dev/null
+                else
+                    cp -R $TMPDIR/$gitreponame/$repodir $WORKING_DIR/$repodir &> /dev/null
+                fi
+                warning "The $repodir directory already exists on your system!"
+                echo "We've backed it up to $repodir-backup, just in case you've changed anything!"
+            else
+                rm -R $WORKING_DIR/$repodir &> /dev/null
+                if [ $gitrepotop != "root" ]; then
+                    cp -R $TMPDIR/$gitreponame/$gitrepotop/$repodir $WORKING_DIR/$repodir &> /dev/null
+                else
+                    cp -R $TMPDIR/$gitreponame/$repodir $WORKING_DIR/$repodir &> /dev/null
+                fi
             fi
         done
+        newline
+        success "Resources for your $productname were copied to"
+        echo  "$WORKING_DIR/"
+        rm -rf $TMPDIR
     fi
 
 # additional install
 
-    newline
-    echo "Checking for additional software..."
-
-    moredepreq=false
-
-    for moredep in ${moreaptdep[@]}
-        do if apt_pkg_req "$moredep"; then
-            moredepreq=true
-        fi
-        done
-    for moredep in ${morepipdep[@]}
-        do if pip_pkg_req "$moredep"; then
-            moredepreq=true
-        fi
-        done
-
-    if $moredepreq; then
+    if ! $MIN_INSTALL; then
         newline
-        echo "Some $productname examples/plugins"
-        echo "require additional software and/or modules"
-        if confirm "Would you like to install them now?"; then
-            for moredep in ${moreaptdep[@]}; do
-                if apt_pkg_req "$moredep"; then
-                    apt_pkg_install "$moredep"
-                fi
+        echo "Checking for additional software..."
+    
+        moredepreq=false
+    
+        for moredep in ${moreaptdep[@]}
+            do if apt_pkg_req "$moredep"; then
+                moredepreq=true
+            fi
             done
-            for moredep in ${morepipdep[@]}; do
-                if pip_pkg_req "$moredep"; then
-                    sudo pip install "$moredep"
-                    sudo $PIP3_BIN install "$moredep"
-                fi
+        for moredep in ${morepipdep[@]}
+            do if pip_pkg_req "$moredep"; then
+                moredepreq=true
+            fi
             done
+    
+        if $moredepreq; then
+            newline
+            echo "Some $productname examples/plugins"
+            echo "require additional software and/or modules"
+            if confirm "Would you like to install them now?"; then
+                for moredep in ${moreaptdep[@]}; do
+                    if apt_pkg_req "$moredep"; then
+                        apt_pkg_install "$moredep"
+                    fi
+                done
+                for moredep in ${morepipdep[@]}; do
+                    if pip_pkg_req "$moredep"; then
+                        sudo pip install "$moredep"
+                        sudo $PIP3_BIN install "$moredep"
+                    fi
+                done
+            fi
+        else
+            success "Done!"
         fi
-    else
-        success "Done!"
     fi
 
 # script custom routines
 
     if [ $customcmd == "no" ]; then
-        newline
-        echo "Finalising Install..."
-        newline
-        sysclean
+        if [ -n "$pkgaptremove" ]; then
+            newline
+            echo "Finalising Install..."
+            newline
+            sysclean
+        fi
         newline
         success "All done!"
         newline
