tries to skip some dependencies if no X running

diff --git a/installers/dashboard b/installers/dashboard
--- a/installers/dashboard
+++ b/installers/dashboard
@@ -62,14 +62,14 @@ repoinstall="no" # whether the library should be installed from repo
 libdir="na" # subdirectory of library in repo
 copydir=() # subdirectories to copy from repo
 pkgaptremove=() # list of conflicting packages to remove
-pkgdeplist1=( "whiptail" "zenity" ) # list of core dependencies
+pkgdeplist1=( "whiptail" ) # list of core dependencies
 pkgdeplist2=() # list of python 2 dependencies
 pkgdeplist3=() # list of python 3 dependencies
-moreaptdep=() # list of additional apt dependencies
+moreaptdep=( "scrot" "zenity" ) # list of additional apt dependencies
 pipdeplist=() # list of dependencies to source from pip
 morepipdep=() # list of additional pip dependencies
 
-# template 1611180210
+# template 1612021245
 
 FORCE=$1
 ASK_TO_REBOOT=false
@@ -692,14 +692,16 @@ if confirm "Do you wish to continue?"; then
 
 # minimum install routine
 
-    if [ $gitrepoclone != "yes" ] && [ $mininstall != "yes" ]; then
-        newline
-        echo "$productname comes with examples and documentation that you may wish to install."
-        echo "Performing a full install will ensure those resources are installed,"
-        echo "along with all required dependencies. It may however take a while!"
-        newline
-
-        if ! confirm "Do you wish to perform a full install?"; then
+        if [ $gitrepoclone != "yes" ] && [ -n $copydir ]; then
+            newline
+            echo "$productname comes with examples and documentation that you may wish to install."
+            echo "Performing a full install will ensure those resources are installed,"
+            echo "along with all required dependencies. It may however take a while!"
+            newline
+            if ! confirm "Do you wish to perform a full install?"; then
+                MIN_INSTALL=true
+            fi
+        elif [ $mininstall == "yes" ] && [ -z "$DISPLAY" ]; then
             MIN_INSTALL=true
         fi
     fi
