debug FAILED_PKG

diff --git a/installers/debug b/installers/debug
--- a/installers/debug
+++ b/installers/debug
@@ -45,7 +45,7 @@ oswarning=( "Debian" "Kali" "Ubuntu" ) # list experimental os-releases
 osdeny=( "Darwin" ) # list os-releases specifically disallowed
 debpackage="blinkt" # the name of the package in apt repo
 piplibname="blinkt" # the name of the lib in pip repo
-pipoverride="yes" # whether the script should give priority to pip repo
+pipoverride="no" # whether the script should give priority to pip repo
 pip2support="yes" # whether python2 is supported
 pip3support="yes" # whether python3 is supported
 topdir="Pimoroni" # the name of the top level directory
@@ -68,7 +68,7 @@ moreaptdep=( "python-numpy" "python-psutil" "python-requests" "python-tweepy" "p
 pipdeplist=() # list of dependencies to source from pip
 morepipdep=() # list of additional pip dependencies
 
-# template 1610311655
+# template 1611040025
 
 FORCE=$1
 ASK_TO_REBOOT=false
@@ -591,13 +591,15 @@ if confirm "Do you wish to continue?"; then
             ASK_TO_REBOOT=true
         fi
         newline && echo "Checking packages required by I2C interface..." && newline
-        if ! apt_pkg_install "python-smbus" /dev/null; then
-            if python --version | grep "2.7" > /dev/null; then
-                echo "python-smbus can't be found, fetching from alternative location..."
-                FAILED_PKG=false
-                DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX` && cd $DEBDIR
-                wget $RASPOOL/main/i/i2c-tools/$SMBUS2 &> /dev/null
-                sudo dpkg -i $DEBDIR/$SMBUS2
+        if apt_pkg_req "python-smbus"; then
+            if ! apt_pkg_install "python-smbus" /dev/null; then
+                if python --version | grep "2.7" > /dev/null; then
+                    echo "python-smbus can't be found, fetching from alternative location..."
+                    FAILED_PKG=false
+                    DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX` && cd $DEBDIR
+                    wget $RASPOOL/main/i/i2c-tools/$SMBUS2 &> /dev/null
+                    sudo dpkg -i $DEBDIR/$SMBUS2
+                fi
             fi
         fi
         if apt_pkg_req "python3-smbus" && apt_pkg_req "python3-smbus1"; then
@@ -879,7 +881,6 @@ if confirm "Do you wish to continue?"; then
         newline
     fi
 
-    FAILED_PKG=false # added temporarily while bug investigated
     if $FAILED_PKG; then
         warning "Some packages could not be installed, review the output for details!" && newline
     fi
