debug for clean-shutdown using phatbeat

diff --git a/installers/debug b/installers/debug
--- a/installers/debug
+++ b/installers/debug
@@ -21,17 +21,17 @@ DISCLAIMER
 
 # script control variables
 
-productname="Blinkt!" # the name of the product to install
-scriptname="blinkt" # the name of this script
+productname="Clean Shutdown Debug" # the name of the product to install
+scriptname="debug" # the name of this script
 spacereq=50 # minimum size required on root partition in MB
 debugmode="no" # whether the script should use debug routines
 debuguser="none" # optional test git user to use in debug mode
 debugpoint="none" # optional git repo branch or tag to checkout
 forcesudo="no" # whether the script requires to be ran with root privileges
-promptreboot="no" # whether the script should always prompt user to reboot
-mininstall="no" # whether the script enforces minimum install routine
-customcmd="no" # whether to execute commands specified before exit
-gpioreq="yes" # whether low-level gpio access is required
+promptreboot="yes" # whether the script should always prompt user to reboot
+mininstall="yes" # whether the script enforces minimum install routine
+customcmd="yes" # whether to execute commands specified before exit
+gpioreq="no" # whether low-level gpio access is required
 i2creq="no" # whether the i2c interface is required
 i2sreq="no" # whether the i2s interface is required
 spireq="no" # whether the spi interface is required
@@ -41,36 +41,36 @@ armv6="yes" # whether armv6 processors are supported
 armv7="yes" # whether armv7 processors are supported
 armv8="yes" # whether armv8 processors are supported
 raspbianonly="no" # whether the script is allowed to run on other OSes
-osreleases=( "Raspbian" "Kano" "Mate" "PiTop" "RetroPie" ) # list os-releases supported
-oswarning=( "Debian" "Kali" "Ubuntu" "Volumio" ) # list experimental os-releases
-osdeny=( "Darwin" "Linaro" ) # list os-releases specifically disallowed
-debpackage="blinkt" # the name of the package in apt repo
-piplibname="blinkt" # the name of the lib in pip repo
+osreleases=( "Raspbian" ) # list os-releases supported
+oswarning=( "OSMC" "Kano" "Mate" "PiTop" "RetroPie" "Volumio" ) # list experimental os-releases
+osdeny=( "Darwin" "Debian" "Kali" "Linaro" "Ubuntu" ) # list os-releases specifically disallowed
+debpackage="na" # the name of the package in apt repo
+piplibname="na" # the name of the lib in pip repo
 pipoverride="no" # whether the script should give priority to pip repo
-pip2support="yes" # whether python2 is supported
-pip3support="yes" # whether python3 is supported
+pip2support="no" # whether python2 is supported
+pip3support="no" # whether python3 is supported
 topdir="Pimoroni" # the name of the top level directory
-localdir="blinkt" # the name of the dir for copy of resources
-gitreponame="blinkt" # the name of the git project repo
+localdir="na" # the name of the dir for copy of resources
+gitreponame="clean-shutdown" # the name of the git project repo
 gitusername="pimoroni" # the name of the git user to fetch repo from
 gitrepobranch="master" # repo branch to checkout
 gitrepotop="root" # the name of the dir to base repo from
-gitrepoclone="no" # whether the git repo is to be cloned locally
+gitrepoclone="yes" # whether the git repo is to be cloned locally
 gitclonedir="source" # the name of the local dir for repo
-repoclean="no" # whether any git repo clone found should be cleaned up
+repoclean="yes"  # whether any git repo clone found should be cleaned up
 repoinstall="no" # whether the library should be installed from repo
-libdir="library" # subdirectory of library in repo
-copydir=( "documentation" "examples" ) # subdirectories to copy from repo
-copyhead="no" # whether to use the latest repo commit or release tag
+libdir="na" # subdirectory of library in repo
+copydir=() # subdirectories to copy from repo
+copyhead="yes" # whether to use the latest repo commit or release tag
 pkgremove=() # list of conflicting packages to remove
-coredeplist=() # list of core dependencies
+coredeplist=( "raspi-gpio" ) # list of core dependencies
 pythondep=() # list of python dependencies
 pipdeplist=() # list of dependencies to source from pypi
-examplesdep=( "numpy" "psutil" "requests" "tweepy" ) # list of python modules required by examples
+examplesdep=() # list of python modules required by examples
 somemoredep=() # list of additional dependencies
 xdisplaydep=() # list of dependencies requiring X server
 
-# template 1704060015
+# template 1705161420
 
 FORCE=$1
 ASK_TO_REBOOT=false
@@ -222,6 +222,8 @@ os_check() {
         OS_NAME="PiTop"
     elif command -v emulationstation > /dev/null; then
         OS_NAME="RetroPie"
+    elif cat /etc/os-release | grep -q "OSMC"; then
+        OS_NAME="OSMC"
     elif cat /etc/os-release | grep -q "volumio"; then
         OS_NAME="Volumio"
     elif cat /etc/os-release | grep -q "Raspbian"; then
@@ -291,7 +293,7 @@ timestamp() {
 }
 
 check_network() {
-    sudo ping -q -w 1 -c 1 `ip r | grep default | cut -d ' ' -f 3 | head -n 1` &> /dev/null && return 0 || return 1
+    sudo ping -q -w 1 -c 1 8.8.8.8 | grep "1 received" &> /dev/null && return 0 || return 1
 }
 
 launch_url() {
@@ -299,7 +301,7 @@ launch_url() {
     if command -v xdg-open > /dev/null; then
         xdg-open "$1" && return 0
     else
-      error_box "There was an error attempting to launch your browser!"
+        error_box "There was an error attempting to launch your browser!"
     fi
 }
 
@@ -453,8 +455,8 @@ disable_pulseaudio() {
 }
 
 kill_volumealsa() {
-    sed -i "s|type=volumealsa|type=space|" $HOME/.config/lxpanel/LXDE/panels/panel
-    sed -i "s|type=volumealsa|type=space|" $HOME/.config/lxpanel/LXDE-pi/panels/panel
+    sed -i "s|type=volumealsa|type=space|" $HOME/.config/lxpanel/LXDE/panels/panel &> /dev/null
+    sed -i "s|type=volumealsa|type=space|" $HOME/.config/lxpanel/LXDE-pi/panels/panel &> /dev/null
 }
 
 basic_asound() {
@@ -1077,24 +1079,27 @@ if confirm "Do you wish to continue?"; then
         echo -e "\nAll done. Enjoy your $productname!\n"
     else # custom block starts here
         echo -e "\nFinalising Install...\n"
-        # place all custom commands in this scope
+        cd $installdir/$gitclonedir && ./setup.sh -y phatbeat
+        cd $installdir && rm -r $installdir/$gitclonedir &> /dev/null
     fi
 
     if $FAILED_PKG; then
-        warning "Some packages could not be installed, review the output for details!\n"
+        warning "Some packages could not be installed, review the output for details!"
+        newline
     fi
     if $IS_EXPERIMENTAL; then
         warning "Support for your operating system is experimental. Please visit"
-        warning "forums.pimoroni.com if you experience issues with this product.\n"
+        warning "forums.pimoroni.com if you experience issues with this product."
+        newline
     fi
 
-    if [ "$FORCE" != '-y' ]; then
+    if [ "$1" != '-y' ]; then
         if [ $promptreboot == "yes" ] || $ASK_TO_REBOOT; then
             sysreboot && newline
         fi
     fi
 else
-    echo -e "\nAborting...\n"
+    newline && echo "Aborting..." && newline
 fi
 
 exit 0
