wip with apt package handling merged in

diff --git a/installers/debug b/installers/debug
--- a/installers/debug
+++ b/installers/debug
@@ -21,8 +21,8 @@ DISCLAIMER
 
 # script control variables
 
-productname="productname" # the name of the product to install
-scriptname="scriptname" # the name of this script
+productname="debug" # the name of the product to install
+scriptname="debug" # the name of this script
 spacereq=50 # minimum size required on root partition in MB
 debugmode="no" # whether the script should use debug routines
 debuguser="none" # optional test git user to use in debug mode
@@ -35,28 +35,25 @@ i2creq="no" # whether the i2c interface is required
 i2sreq="no" # whether the i2s interface is required
 spireq="no" # whether the spi interface is required
 uartreq="no" # whether uart communication is required
-armhfonly="yes" # whether the script is allowed to run on other arch
+armhfonly="no" # whether the script is allowed to run on other arch
 armv6="yes" # whether armv6 processors are supported
 armv7="yes" # whether armv7 processors are supported
 armv8="yes" # whether armv8 processors are supported
 raspbianonly="no" # whether the script is allowed to run on other OSes
-osreleases=( "Raspbian" ) # list os-releases supported
-oswarning=( "Debian" "Mate" "PiTop" "Ubuntu" ) # list experimental os-releases
+osreleases=( "Raspbian" "Mate" "PiTop" ) # list os-releases supported
+oswarning=( "Debian" "Ubuntu" ) # list experimental os-releases
 osdeny=( "Darwin" "Kali" ) # list os-releases specifically disallowed
-squeezesupport="no" # whether Squeeze is supported
-wheezysupport="yes" # whether Wheezy is supported
-jessiesupport="yes" # whether Jessie is supported
-debpackage="aptdebname" # the name of the package in apt repo
-piplibname="piplibname" # the name of the lib in pip repo
+debpackage="na" # the name of the package in apt repo
+piplibname="mote" # the name of the lib in pip repo
 pipoverride="yes" # whether the script should give priority to pip repo
 pip2support="yes" # whether python2 is supported
 pip3support="yes" # whether python3 is supported
 topdir="Pimoroni" # the name of the top level directory
-localdir="localdir" # the name of the dir for copy of resources
-gitreponame="gitreponame" # the name of the git project repo
+localdir="mote" # the name of the dir for copy of resources
+gitreponame="mote" # the name of the git project repo
 gitusername="pimoroni" # the name of the git user to fetch repo from
 gitrepobranch="master" # repo branch to checkout
-gitrepotop="root" # the name of the dir to base repo from
+gitrepotop="python" # the name of the dir to base repo from
 gitrepoclone="no" # whether the git repo is to be cloned locally
 gitclonedir="source" # the name of the local dir for repo
 repoclean="no"  # whether any git repo clone found should be cleaned up
@@ -65,13 +62,13 @@ libdir="library" # subdirectory of library in repo
 copydir=( "documentation" "examples" ) # subdirectories to copy from repo
 pkgaptremove=() # list of conflicting packages to remove
 pkgdeplist1=() # list of core dependencies
-pkgdeplist2=() # list of python 2 dependencies
-pkgdeplist3=() # list of python 3 dependencies
-moreaptdep=() # list of additional apt dependencies
+pkgdeplist2=( "python-serial" ) # list of python 2 dependencies
+pkgdeplist3=( "python3-serial" ) # list of python 3 dependencies
+moreaptdep=( "python-liboost" ) # list of additional apt dependencies
 pipdeplist=() # list of dependencies to source from pip
 morepipdep=() # list of additional pip dependencies
 
-# template 1609301205
+# template 1610251930
 
 FORCE=$1
 ASK_TO_REBOOT=false
@@ -186,7 +183,7 @@ os_check() {
 
     if [ -f /etc/os-release ]; then
         if cat /etc/os-release | grep "Raspbian" > /dev/null; then
-            IS_RASPBIAN=true && IS_SUPPORTED=true
+            IS_RASPBIAN=true
         fi
         if command -v apt-get > /dev/null; then
             for os in ${osreleases[@]}; do
@@ -206,7 +203,7 @@ os_check() {
             done
         fi
     fi
-    if [ -f ~/.pt-dashboard-config ]; then
+    if [ -f ~/.pt-dashboard-config ] || [ -d ~/.pt-dashboard ]; then
         IS_RASPBIAN=false
         for os in ${oswarning[@]}; do
             if [ $os == "PiTop" ]; then
@@ -237,29 +234,21 @@ os_check() {
 }
 
 raspbian_check() {
-    IS_SQUEEZE=false
-    IS_WHEEZY=false
-    IS_JESSIE=false
+    IS_SUPPORTED=false
+    IS_EXPERIMENTAL=false
 
     if [ -f /etc/os-release ]; then
-        if cat /etc/os-release | grep "jessie" > /dev/null; then
-            IS_JESSIE=true
+        if cat /etc/os-release | grep "/sid" > /dev/null; then
+            IS_SUPPORTED=false && IS_EXPERIMENTAL=true
+        elif cat /etc/os-release | grep "stretch" > /dev/null; then
+            IS_SUPPORTED=false && IS_EXPERIMENTAL=true
+        elif cat /etc/os-release | grep "jessie" > /dev/null; then
+            IS_SUPPORTED=true && IS_EXPERIMENTAL=false
         elif cat /etc/os-release | grep "wheezy" > /dev/null; then
-            IS_WHEEZY=true
-        elif cat /etc/os-release | grep "squeeze" > /dev/null; then
-            IS_SQUEEZE=true
+            IS_SUPPORTED=true && IS_EXPERIMENTAL=false
         else
-            echo "Unsupported distribution"
-            exit 1
+            IS_SUPPORTED=false && IS_EXPERIMENTAL=false
         fi
-    fi
-}
-
-raspbian_old() {
-    if $IS_SQUEEZE || $IS_WHEEZY ;then
-        true
-    else
-        false
     fi
 }
 
@@ -284,40 +273,6 @@ home_dir() {
     fi
 }
 
-servd_trig() {
-    if command -v service > /dev/null; then
-        sudo service $1 $2
-    fi
-}
-
-get_init_sys() {
-    if command -v systemctl > /dev/null && systemctl | grep -q '\-\.mount'; then
-        SYSTEMD=1
-    elif [ -f /etc/init.d/cron ] && [ ! -h /etc/init.d/cron ]; then
-        SYSTEMD=0
-    else
-        echo "Unrecognised init system" && exit 1
-    fi
-}
-
-i2c_vc_dtparam() {
-    if [ -e $CONFIG ] && grep -q "^dtparam=i2c_vc=on$" $CONFIG; then
-        newline && echo "i2c0 bus already active"
-    else
-        newline && echo "Enabling i2c0 bus in $CONFIG"
-        echo "dtparam=i2c_vc=on" | sudo tee -a $CONFIG && newline
-    fi
-}
-
-usb_max_power() {
-    if [ -e $CONFIG ] && grep -q "^max_usb_current=1$" $CONFIG; then
-        newline && echo "Max USB current setting already active"
-    else
-        newline && echo "Adjusting USB current setting in $CONFIG"
-        echo "max_usb_current=1" | sudo tee -a $CONFIG && newline
-    fi
-}
-
 space_chk() {
     if command -v stat > /dev/null && ! $IS_MACOSX; then
         if [ $spacereq -gt $(($(stat -f -c "%a*%S" /)/10**6)) ];then
@@ -338,21 +293,24 @@ timestamp() {
 }
 
 check_network() {
-    sudo ping -q -w 1 -c 1 `ip r | grep default | cut -d ' ' -f 3` &> /dev/null && return 0 || return 1
+    sudo ping -q -w 1 -c 1 `ip r | grep default | cut -d ' ' -f 3 | head -n 1` &> /dev/null && return 0 || return 1
 }
 
 apt_pkg_req() {
     APT_CHK=$(dpkg-query -W -f='${Status}\n' $1 2> /dev/null | grep "install ok installed")
 
     if [ "" == "$APT_CHK" ]; then
+        echo "$1 is required"
         true
     else
+        echo "$1 is already installed"
         false
     fi
 }
 
 apt_pkg_install() {
-    \curl -sS $GETPOOL/package | sudo bash -s - $1 || { warning "Apt failed to install $1!" && FAILED_PKG=true && return 1; }
+    echo "Installing $1..."
+    sudo apt-get --yes install "$1" 1> /dev/null || warning "Apt failed to install $1!" && FAILED_PKG=true
     newline
 }
 
@@ -400,6 +358,40 @@ pip3_pkg_req() {
     fi
 }
 
+usb_max_power() {
+    if [ -e $CONFIG ] && grep -q "^max_usb_current=1$" $CONFIG; then
+        newline && echo "Max USB current setting already active"
+    else
+        newline && echo "Adjusting USB current setting in $CONFIG"
+        echo "max_usb_current=1" | sudo tee -a $CONFIG && newline
+    fi
+}
+
+servd_trig() {
+    if command -v service > /dev/null; then
+        sudo service $1 $2
+    fi
+}
+
+get_init_sys() {
+    if command -v systemctl > /dev/null && systemctl | grep -q '\-\.mount'; then
+        SYSTEMD=1
+    elif [ -f /etc/init.d/cron ] && [ ! -h /etc/init.d/cron ]; then
+        SYSTEMD=0
+    else
+        echo "Unrecognised init system" && exit 1
+    fi
+}
+
+i2c_vc_dtparam() {
+    if [ -e $CONFIG ] && grep -q "^dtparam=i2c_vc=on$" $CONFIG; then
+        newline && echo "i2c0 bus already active"
+    else
+        newline && echo "Enabling i2c0 bus in $CONFIG"
+        echo "dtparam=i2c_vc=on" | sudo tee -a $CONFIG && newline
+    fi
+}
+
 : <<'MAINSTART'
 
 Perform all variables declarations as well as function definition
@@ -441,8 +433,8 @@ fi
 
 arch_check
 os_check
-home_dir
 space_chk
+home_dir
 
 if [ $debugmode != "no" ]; then
     echo "USER_HOME is $USER_HOME" && newline
@@ -455,6 +447,7 @@ fi
 
 if ! $IS_ARMHF; then
     warning "This hardware is not supported, sorry!"
+    warning "Config files have been left untouched"
     newline && exit 1
 fi
 
@@ -476,7 +469,7 @@ fi
 
 if $IS_RASPBIAN; then
     raspbian_check
-    if [ $wheezysupport == "no" ] && raspbian_old; then
+    if ! $IS_SUPPORTED && ! $IS_EXPERIMENTAL; then
         newline && warning "--- Warning ---" && newline
         echo "The $productname installer"
         echo "does not work on this version of Raspbian."
@@ -524,21 +517,21 @@ if confirm "Do you wish to continue?"; then
 
     newline && echo "Checking environment..."
 
-    if ! check_network; then
-        warning "We can't connect to the Internet, check your network!" && exit 1
-    fi
     if [ "$FORCE" != '-y' ]; then
+        if ! check_network; then
+            warning "We can't connect to the Internet, check your network!" && exit 1
+        fi
         sysupdate
-    fi
-    if ! command -v curl > /dev/null; then
-        apt_pkg_install "curl"
-    fi
-    if ! command -v wget > /dev/null; then
-        apt_pkg_install "wget"
-    fi
-    if ! command -v pip > /dev/null; then
-        apt_pkg_install "python-pip"
-        apt_pkg_install "python3-pip"
+        if ! command -v curl > /dev/null; then
+            apt_pkg_install "curl"
+        fi
+        if ! command -v wget > /dev/null; then
+            apt_pkg_install "wget"
+        fi
+        if ! command -v pip > /dev/null; then
+            apt_pkg_install "python-pip"
+            apt_pkg_install "python3-pip"
+        fi
     fi
     pip2_chk && pip3_chk
 
@@ -642,12 +635,13 @@ if confirm "Do you wish to continue?"; then
         fi
     fi
 
+    if [ $localdir != "na" ]; then
+        installdir="$USER_HOME/$topdir/$localdir"
+    else
+        installdir="$USER_HOME/$topdir"
+    fi
+
     if ! $MIN_INSTALL;then
-        if [ $localdir != "na" ]; then
-            installdir="$USER_HOME/$topdir/$localdir"
-        else
-            installdir="$USER_HOME/$topdir"
-        fi
         [ -d $installdir ] || mkdir -p $installdir
     fi
 
@@ -659,7 +653,7 @@ if confirm "Do you wish to continue?"; then
 
     echo "Checking install requirements..."
 
-    newline && echo "Checking for dependencies..."
+    newline && echo "Checking for dependencies..." && newline
 
     if $REMOVE_PKG; then
         for pkgrm in ${pkgaptremove[@]}; do
@@ -758,7 +752,7 @@ if confirm "Do you wish to continue?"; then
 # additional install
 
     if ! $MIN_INSTALL; then
-        newline && echo "Checking for additional software..."
+        newline && echo "Checking for additional software..." && newline
         moredepreq=false
 
         for moredep in ${moreaptdep[@]}; do
