additional messages to confirm Rpi.GPIO, spidev and smbus status

diff --git a/installers/debug b/installers/debug
--- a/installers/debug
+++ b/installers/debug
@@ -68,7 +68,7 @@ moreaptdep=( "python-liboost" ) # list of additional apt dependencies
 pipdeplist=() # list of dependencies to source from pip
 morepipdep=() # list of additional pip dependencies
 
-# template 1610311255
+# template 1610311310
 
 FORCE=$1
 ASK_TO_REBOOT=false
@@ -544,13 +544,14 @@ if confirm "Do you wish to continue?"; then
     newline && echo "Checking hardware requirements..."
 
     if [ $gpioreq == "yes" ]; then
-        newline && echo "Checking for packages required for GPIO control..." && newline
+        newline && echo "Checking for packages required for GPIO control..."
         if ! apt_pkg_install "python-rpi.gpio" &> /dev/null; then
             sudo $PIP2_BIN install RPi.GPIO -U && FAILED_PKG=false
         fi
         if ! apt_pkg_install "python3-rpi.gpio" &> /dev/null; then
             sudo $PIP3_BIN install RPi.GPIO -U && FAILED_PKG=false
         fi
+        echo "Rpi.GPIO installed and up-to-date" && newline
     fi
 
     if [ $spireq == "yes" ]; then
@@ -562,13 +563,14 @@ if confirm "Do you wish to continue?"; then
             \curl -sS $GETPOOL/spi | sudo bash -s - "-y"
             ASK_TO_REBOOT=true
         fi
-        newline && echo "Checking packages required by SPI interface..." && newline
+        newline && echo "Checking packages required by SPI interface..."
         if apt_pkg_req "python-spidev" && ! apt_pkg_install "python-spidev" &> /dev/null; then
             sudo $PIP2_BIN install spidev -U && FAILED_PKG=false
         fi
         if apt_pkg_req "python3-spidev" && ! apt_pkg_install "python3-spidev" &> /dev/null; then
             sudo $PIP3_BIN install spidev -U && FAILED_PKG=false
         fi
+        echo "spidev installed and up-to-date" && newline
     fi
 
     if [ $i2creq == "yes" ]; then
@@ -581,7 +583,7 @@ if confirm "Do you wish to continue?"; then
             ASK_TO_REBOOT=true
         fi
         newline && echo "Checking packages required by I2C interface..." && newline
-        if apt_pkg_req "python-smbus" && ! apt_pkg_install "python-smbus" /dev/null; then
+        if ! apt_pkg_install "python-smbus" /dev/null; then
             if python --version | grep "2.7" > /dev/null; then
                 echo "python-smbus can't be found, fetching from alternative location..."
                 FAILED_PKG=false
@@ -589,10 +591,6 @@ if confirm "Do you wish to continue?"; then
                 wget $RASPOOL/main/i/i2c-tools/$SMBUS2 &> /dev/null
                 sudo dpkg -i $DEBDIR/$SMBUS2
             fi
-        fi
-        if ! $PIP2_BIN list | grep "smbus" > /dev/null; then
-            warning "Unable to install smbus for python 2!"
-            FAILED_PKG=true
         fi
         if apt_pkg_req "python3-smbus" && apt_pkg_req "python3-smbus1"; then
             if ! apt_pkg_install "python3-smbus" /dev/null; then
@@ -616,6 +614,11 @@ if confirm "Do you wish to continue?"; then
         if ! $PIP3_BIN list | grep "smbus" > /dev/null; then
             warning "Unable to install smbus for python 3!"
             FAILED_PKG=true
+        elif ! $PIP2_BIN list | grep "smbus" > /dev/null; then
+            warning "Unable to install smbus for python 2!"
+            FAILED_PKG=true
+        else
+            echo "smbus installed and up-to-date" && newline
         fi
     fi
 
