spurious FAILED_PKG warning fix

diff --git a/installers/drumhat b/installers/drumhat
--- a/installers/drumhat
+++ b/installers/drumhat
@@ -68,7 +68,7 @@ moreaptdep=( "python-pygame" "python3-pygame" ) # list of additional apt depende
 pipdeplist=() # list of dependencies to source from pip
 morepipdep=() # list of additional pip dependencies
 
-# template 1611040025
+# template 1611040130
 
 FORCE=$1
 ASK_TO_REBOOT=false
@@ -314,7 +314,7 @@ apt_pkg_req() {
 
 apt_pkg_install() {
     echo "Installing $1..."
-    sudo apt-get --yes install "$1" 1> /dev/null || warning "Apt failed to install $1!" && FAILED_PKG=true
+    sudo apt-get --yes install "$1" 1> /dev/null || { warning "Apt failed to install $1!" && FAILED_PKG=true; }
     newline
 }
 
@@ -564,10 +564,10 @@ if confirm "Do you wish to continue?"; then
             ASK_TO_REBOOT=true
         fi
         newline && echo "Checking packages required by SPI interface..."
-        if apt_pkg_req "python-spidev" && ! apt_pkg_install "python-spidev" &> /dev/null; then
+        if ! apt_pkg_install "python-spidev" &> /dev/null; then
             sudo $PIP2_BIN install spidev -U && FAILED_PKG=false
         fi
-        if apt_pkg_req "python3-spidev" && ! apt_pkg_install "python3-spidev" &> /dev/null; then
+        if ! apt_pkg_install "python3-spidev" &> /dev/null; then
             sudo $PIP3_BIN install spidev -U && FAILED_PKG=false
         fi
         if ! $PIP3_BIN list | grep "spidev" > /dev/null; then
@@ -591,33 +591,29 @@ if confirm "Do you wish to continue?"; then
             ASK_TO_REBOOT=true
         fi
         newline && echo "Checking packages required by I2C interface..." && newline
-        if apt_pkg_req "python-smbus"; then
-            if ! apt_pkg_install "python-smbus" /dev/null; then
-                if python --version | grep "2.7" > /dev/null; then
-                    echo "python-smbus can't be found, fetching from alternative location..."
-                    FAILED_PKG=false
-                    DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX` && cd $DEBDIR
-                    wget $RASPOOL/main/i/i2c-tools/$SMBUS2 &> /dev/null
-                    sudo dpkg -i $DEBDIR/$SMBUS2
-                fi
+        if ! apt_pkg_install "python-smbus" &> /dev/null; then
+            if python --version | grep "2.7" > /dev/null; then
+                echo "python-smbus can't be found, fetching from alternative location..."
+                FAILED_PKG=false
+                DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX` && cd $DEBDIR
+                wget $RASPOOL/main/i/i2c-tools/$SMBUS2 &> /dev/null
+                sudo dpkg -i $DEBDIR/$SMBUS2
             fi
         fi
-        if apt_pkg_req "python3-smbus" && apt_pkg_req "python3-smbus1"; then
-            if ! apt_pkg_install "python3-smbus" /dev/null; then
-                if python3 --version | grep "3.4" > /dev/null; then
+        if ! apt_pkg_install "python3-smbus" &> /dev/null; then
+            if python3 --version | grep "3.4" > /dev/null; then
+                echo "python3-smbus can't be found, fetching from alternative location..."
+                FAILED_PKG=false
+                DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX` && cd $DEBDIR
+                wget $RASPOOL/main/i/i2c-tools/$SMBUS3 &> /dev/null
+                sudo dpkg -i $DEBDIR/$SMBUS3
+            elif python3 --version | grep "3.5" > /dev/null; then
+                if apt_pkg_req "python3-smbus1" &> /dev/null; then
                     echo "python3-smbus can't be found, fetching from alternative location..."
                     FAILED_PKG=false
                     DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX` && cd $DEBDIR
-                    wget $RASPOOL/main/i/i2c-tools/$SMBUS3 &> /dev/null
-                    sudo dpkg -i $DEBDIR/$SMBUS3
-                elif python3 --version | grep "3.5" > /dev/null; then
-                    if apt_pkg_req "python3-smbus1"; then
-                        echo "python3-smbus can't be found, fetching from alternative location..."
-                        FAILED_PKG=false
-                        DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX` && cd $DEBDIR
-                        wget $GETPOOL/resources/$SMBUS1 &> /dev/null
-                        sudo dpkg -i $DEBDIR/$SMBUS1
-                    fi
+                    wget $GETPOOL/resources/$SMBUS1 &> /dev/null
+                    sudo dpkg -i $DEBDIR/$SMBUS1
                 fi
             fi
         fi
