some tyding up of code

diff --git a/installers/skywriter b/installers/skywriter
--- a/installers/skywriter
+++ b/installers/skywriter
@@ -68,7 +68,7 @@ examplesdep=() # list of python modules required by examples
 somemoredep=( "puredata-core" ) # list of additional dependencies
 xdisplaydep=() # list of dependencies requiring X server
 
-# template 1702222035
+# template 1702222100
 
 FORCE=$1
 ASK_TO_REBOOT=false
@@ -274,8 +274,7 @@ space_chk() {
             echo
             warning  "There is not enough space left to proceed with  installation"
             if confirm "Would you like to attempt to expand your filesystem?"; then
-                \curl -sS $GETPOOL/expandfs | sudo bash
-                exit 1
+                curl -sS $GETPOOL/expandfs | sudo bash && exit 1
             else
                 echo && exit 1
             fi
@@ -308,7 +307,7 @@ get_install() {
     if ! command -v curl > /dev/null; then
         apt_pkg_install "curl"
     fi
-    \curl -sS https://get.pimoroni.com/$1 | bash -s - "-y"
+    curl -sS https://get.pimoroni.com/$1 | bash -s - "-y"
     read -p "Press Enter to continue..." < /dev/tty
 }
 
@@ -635,23 +634,21 @@ if confirm "Do you wish to continue?"; then
 
 # hardware setup
 
-    newline && echo "Checking hardware requirements..."
+    echo -e "\nChecking hardware requirements..."
 
     if [ $uartreq == "yes" ]; then
-        newline && echo "The serial console must be disabled for $productname to work"
-        \curl -sS $GETPOOL/uarton | sudo bash -s - "-y"
-        ASK_TO_REBOOT=true && newline
+        echo -e "\nThe serial console must be disabled for $productname to work"
+        curl -sS $GETPOOL/uarton | sudo bash -s - "-y" && ASK_TO_REBOOT=true
     fi
 
     if [ $gpioreq == "yes" ]; then
-        newline && echo "Checking for packages required for GPIO control..."
+        echo -e "\nChecking for packages required for GPIO control..."
         if [ "$pip2support" == "yes" ] && ! apt_pkg_install "python-rpi.gpio" &> /dev/null; then
             if [ -n $(python --version 2>&1 | grep -q "2.7") ]; then
                 echo "python-rpi.gpio can't be found, fetching from alternative location..."
-                FAILED_PKG=false
                 DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX` && cd $DEBDIR
                 wget $RPIPOOL/main/r/rpi.gpio/$RPIGPIO2 &> /dev/null
-                sudo dpkg -i $DEBDIR/$RPIGPIO2
+                sudo dpkg -i $DEBDIR/$RPIGPIO2 && FAILED_PKG=false
             else
                 sudo $PIP2_BIN install RPi.GPIO && FAILED_PKG=false
             fi
@@ -659,32 +656,31 @@ if confirm "Do you wish to continue?"; then
         if [ "$pip3support" == "yes" ] && ! apt_pkg_install "python3-rpi.gpio" &> /dev/null; then
             if [ -n $(python3 --version 2>&1 | grep -q "3.4") ]; then
                 echo "python3-rpi.gpio can't be found, fetching from alternative location..."
-                FAILED_PKG=false
                 DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX` && cd $DEBDIR
                 wget $RPIPOOL/main/r/rpi.gpio/$RPIGPIO3 &> /dev/null
-                sudo dpkg -i $DEBDIR/$RPIGPIO3
+                sudo dpkg -i $DEBDIR/$RPIGPIO3 && FAILED_PKG=false
             else
                 sudo $PIP3_BIN install RPi.GPIO && FAILED_PKG=false
             fi
         fi
         if [ "$pip2support" == "yes" ] && [ -f "$(which python2)" ]; then
             if ! $PIP2_BIN list | grep "RPi.GPIO" &> /dev/null; then
-                warning "Unable to install RPi.GPIO for python 2!"
-                FAILED_PKG=true
+                warning "Unable to install RPi.GPIO for python 2!" && FAILED_PKG=true
+            else
+                RPIGPIO2="install ok installed"
             fi
-        else
-            RPIGPIO2=""
         fi
         if [ "$pip3support" == "yes" ] && [ -f "$(which python3)" ]; then
             if ! $PIP3_BIN list | grep "RPi.GPIO" &> /dev/null; then
-                warning "Unable to install RPi.GPIO for python 3!"
-                FAILED_PKG=true
+                warning "Unable to install RPi.GPIO for python 3!" && FAILED_PKG=true
+            else
+                RPIGPIO3="install ok installed"
             fi
-        else
-            RPIGPIO3=""
         fi
-        if [ -z "$RPIGPIO2" ] && [ -z "$RPIGPIO3" ]; then
-            echo "RPi.GPIO installed and up-to-date" && newline
+        if [ "$RPIGPIO2" == "install ok installed" ] || [ "$RPIGPIO3" == "install ok installed" ]; then
+            if ! FAILED_PKG; then
+                echo -e "RPi.GPIO installed and up-to-date\n"
+            fi
         fi
     fi
 
@@ -698,18 +694,16 @@ if confirm "Do you wish to continue?"; then
                 sudo raspi-config nonint do_spi 0
                 inform "SPI is now enabled"
             else
-                \curl -sS $GETPOOL/spi | sudo bash -s - "-y"
-                ASK_TO_REBOOT=true
+                curl -sS $GETPOOL/spi | sudo bash -s - "-y" && ASK_TO_REBOOT=true
             fi
         fi
-        newline && echo "Checking packages required by SPI interface..."
+        echo -e "\nChecking packages required by SPI interface..."
         if [ "$pip2support" == "yes" ] && ! apt_pkg_install "python-spidev" &> /dev/null; then
             if [ -n $(python --version 2>&1 | grep -q "2.7") ]; then
                 echo "python-spidev can't be found, fetching from alternative location..."
-                FAILED_PKG=false
                 DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX` && cd $DEBDIR
                 wget $RPIPOOL/main/s/spidev/$SPIDEV2 &> /dev/null
-                sudo dpkg -i $DEBDIR/$SPIDEV2
+                sudo dpkg -i $DEBDIR/$SPIDEV2 && FAILED_PKG=false
             else
                 sudo $PIP2_BIN install spidev && FAILED_PKG=false
             fi
@@ -717,32 +711,31 @@ if confirm "Do you wish to continue?"; then
         if [ "$pip3support" == "yes" ] && ! apt_pkg_install "python3-spidev" &> /dev/null; then
             if [ -n $(python3 --version 2>&1 | grep -q "3.4") ]; then
                 echo "python3-spidev can't be found, fetching from alternative location..."
-                FAILED_PKG=false
                 DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX` && cd $DEBDIR
                 wget $RPIPOOL/main/s/spidev/$SPIDEV3 &> /dev/null
-                sudo dpkg -i $DEBDIR/$SPIDEV3
+                sudo dpkg -i $DEBDIR/$SPIDEV3 && FAILED_PKG=false
             else
                 sudo $PIP3_BIN install spidev && FAILED_PKG=false
             fi
         fi
         if [ "$pip2support" == "yes" ] && [ -f "$(which python2)" ]; then
             if ! $PIP2_BIN list | grep "spidev" &> /dev/null; then
-                warning "Unable to install spidev for python 2!"
-                FAILED_PKG=true
+                warning "Unable to install spidev for python 2!" && FAILED_PKG=true
             else
-                SPIDEV3="yes"
+                SPIDEV3="install ok installed"
             fi
         fi
         if [ "$pip3support" == "yes" ] && [ -f "$(which python3)" ]; then
             if ! $PIP3_BIN list | grep "spidev" &> /dev/null; then
-                warning "Unable to install spidev for python 3!"
-                FAILED_PKG=true
+                warning "Unable to install spidev for python 3!" && FAILED_PKG=true
             else
-                SPIDEV2="yes"
+                SPIDEV2="install ok installed"
             fi
         fi
-        if [ "$SPIDEV2" == "yes" ] && [ "$SPIDEV3" == "yes" ]; then
-            echo "spidev installed and up-to-date" && newline
+        if [ "$SPIDEV2" == "install ok installed" ] && [ "$SPIDEV3" == "install ok installed" ]; then
+            if ! FAILED_PKG; then
+                echo -e "spidev installed and up-to-date\n"
+            fi
         fi
     fi
 
@@ -756,55 +749,51 @@ if confirm "Do you wish to continue?"; then
                 sudo raspi-config nonint do_i2c 0
                 inform "I2C is now enabled"
             else
-                \curl -sS $GETPOOL/i2c | sudo bash -s - "-y"
-                ASK_TO_REBOOT=true
+                curl -sS $GETPOOL/i2c | sudo bash -s - "-y" && ASK_TO_REBOOT=true
             fi
         fi
-        newline && echo "Checking packages required by I2C interface..."
+        echo -e "\nChecking packages required by I2C interface..."
         if [ "$pip2support" == "yes" ] && ! apt_pkg_install "python-smbus" &> /dev/null; then
             if [ -n $(python --version 2>&1 | grep -q "2.7") ]; then
                 echo "python-smbus can't be found, fetching from alternative location..."
-                FAILED_PKG=false
                 DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX` && cd $DEBDIR
                 wget $RPIPOOL/main/i/i2c-tools/$SMBUS2 &> /dev/null
-                sudo dpkg -i $DEBDIR/$SMBUS2
+                sudo dpkg -i $DEBDIR/$SMBUS2 && FAILED_PKG=false
             fi
         fi
         if [ "$pip3support" == "yes" ] && ! apt_pkg_install "python3-smbus" &> /dev/null; then
             if [ -n $(python3 --version 2>&1 | grep -q "3.4") ]; then
                 echo "python3-smbus can't be found, fetching from alternative location..."
-                FAILED_PKG=false
                 DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX` && cd $DEBDIR
                 wget $RPIPOOL/main/i/i2c-tools/$SMBUS3 &> /dev/null
-                sudo dpkg -i $DEBDIR/$SMBUS3
+                sudo dpkg -i $DEBDIR/$SMBUS3 && FAILED_PKG=false
             elif [ -n $(python3 --version 2>&1 | grep -q "3.5") ]; then
                 if apt_pkg_req "python3-smbus1" &> /dev/null; then
                     echo "python3-smbus can't be found, fetching from alternative location..."
-                    FAILED_PKG=false
                     DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX` && cd $DEBDIR
                     wget $GETPOOL/resources/$SMBUS35 &> /dev/null
-                    sudo dpkg -i $DEBDIR/$SMBUS35
+                    sudo dpkg -i $DEBDIR/$SMBUS35 && FAILED_PKG=false
                 fi
             fi
         fi
         if [ "$pip2support" == "yes" ] && [ -f "$(which python2)" ]; then
             if ! $PIP2_BIN list | grep "smbus" &> /dev/null; then
-                warning "Unable to install smbus for python 2!"
-                FAILED_PKG=true
+                warning "Unable to install smbus for python 2!" && FAILED_PKG=true
             else
-                SMBUS3="yes"
+                SMBUS3="install ok installed"
             fi
         fi
         if [ "$pip3support" == "yes" ] && [ -f "$(which python3)" ]; then
             if ! $PIP3_BIN list | grep "smbus" &> /dev/null; then
-                warning "Unable to install smbus for python 3!"
-                FAILED_PKG=true
+                warning "Unable to install smbus for python 3!" && FAILED_PKG=true
             else
-                SMBUS2="yes"
+                SMBUS2="install ok installed"
             fi
         fi
-        if [ "$SMBUS2" == "yes" ] && [ "$SMBUS3" == "yes" ]; then
-            echo "smbus installed and up-to-date" && newline
+        if [ "$SMBUS2" == "install ok installed" ] && [ "$SMBUS3" == "install ok installed" ]; then
+            if ! FAILED_PKG; then
+                echo -e "smbus installed and up-to-date\n"
+            fi
         fi
     fi
 
