Ubuntu/Debian osrelease

diff --git a/installers/unicornhat b/installers/unicornhat
--- a/installers/unicornhat
+++ b/installers/unicornhat
@@ -32,10 +32,13 @@ customcmd="yes" # whether to execute commands specified before exit
 i2creq="no" # whether i2c is required or not
 spireq="no" # whether spi is required or not
 uartreq="no" # whether uart communication is required or not
+armhfonly="yes" # whether the script is allowed to run on other arch
 armv6="yes" # whether armv6 processors is supported or not
 armv7="yes" # whether armv7 processors is supported or not
 armv8="yes" # whether armv8 processors is supported or not
 raspbianonly="no" # whether the script is allowed to run on other OSes
+macosxsupport="no" # whether Mac OS X is supported by the script
+osreleases=( "Raspbian" "Ubuntu" "Debian" ) # list all the os-releases supported
 squeezesupport="no" # whether Squeeze is supported or not
 wheezysupport="yes" # whether Wheezy is supported or not
 jessiesupport="yes" # whether Jessie is supported or not
@@ -67,7 +70,7 @@ moreaptdep=( "git" "python-numpy" "python3-numpy" "python-flask" "python3-flask"
 morepipdep=() # list of all the additional pip dependencies
 spacereq=150 # minimum size required on root partition in MB
 
-# template 1609012005
+# template 1609030145
 
 FORCE=$1
 DEVICE_TREE=true
@@ -75,6 +78,7 @@ ASK_TO_REBOOT=false
 CURRENT_SETTING=false
 MIN_INSTALL=false
 REMOVE_PKG=false
+FAILED_PKG=false
 
 BOOTCMD=/boot/cmdline.txt
 CONFIG=/boot/config.txt
@@ -83,7 +87,7 @@ INITABCONF=/etc/inittab
 BLACKLIST=/etc/modprobe.d/raspi-blacklist.conf
 LOADMOD=/etc/modules
 
-RASPOOL="http://archive.raspbian.org/raspbian/pool"
+RASPOOL="http://archive.raspberrypi.org/debian/pool"
 DEBPOOL="http://ftp.uk.debian.org/debian/pool"
 
 # function define
@@ -155,27 +159,38 @@ sysreboot() {
 }
 
 arch_check() {
+    IS_ARMHF=false
     IS_ARMv6=false
 
-    if uname -m | grep "armv6l" > /dev/null; then
-        IS_ARMv6=true
+    if uname -m | grep "armv.l" > /dev/null; then
+        IS_ARMHF=true
+        if uname -m | grep "armv6l" > /dev/null; then
+            IS_ARMv6=true
+        fi
     fi
 }
 
 os_check() {
     IS_RASPBIAN=false
     IS_MACOSX=false
-    IS_X86_64=false
-    IS_X86_32=false
+    IS_SUPPORTED=false
 
-    if [ -f /etc/os-release ] && cat /etc/os-release | grep "Raspbian" > /dev/null; then
-        IS_RASPBIAN=true
+    if [ -f /etc/os-release ]; then
+        if cat /etc/os-release | grep "Raspbian" > /dev/null; then
+            IS_RASPBIAN=true && IS_SUPPORTED=true
+        fi
+        if command -v apt-get &> /dev/null; then
+            for os in ${osreleases[@]}; do
+                if cat /etc/os-release | grep "$os" > /dev/null; then
+                    IS_SUPPORTED=true
+                fi
+            done
+        fi
     elif uname -s | grep "Darwin" > /dev/null; then
         IS_MACOSX=true
-    elif uname -m | grep "x86_64" > /dev/null; then
-        IS_X86_64=true
-    else
-        IS_X86_32=true
+        if [ $macosxsupport == "yes" ]; then
+            IS_SUPPORTED=true
+        fi
     fi
 }
 
@@ -320,7 +335,7 @@ apt_pkg_req() {
 }
 
 apt_pkg_install() {
-    \curl -sS https://get.pimoroni.com/package | sudo bash -s - $1 || { warning "Sorry, Apt failed to install $1, I can't continue!" && exit 1; }
+    \curl -sS https://get.pimoroni.com/package | sudo bash -s - $1 || { warning "Apt failed to install $1!" && FAILED_PKG=true; }
 }
 
 pip_pkg_req() {
@@ -406,40 +421,30 @@ if [ "$FORCE" != '-y' ]; then
     space_chk
 fi
 
-if $IS_RASPBIAN; then
-    raspbian_check
-    if [ $squeezesupport == "no" ] && $IS_SQUEEZE; then
-        newline
-        warning "--- Warning ---"
-        newline
-        echo "The $productname installer"
-        echo "does not work on this version of Raspbian."
-        echo "Check https://github.com/$gitusername/$gitreponame"
-        echo "for additional information and support"
-        newline
-        exit 1
-    elif [ $wheezysupport == "no" ] && $IS_WHEEZY; then
-        newline
-        warning "--- Warning ---"
-        newline
-        echo "The $productname installer"
-        echo "does not work on this version of Raspbian."
-        echo "Check https://github.com/$gitusername/$gitreponame"
-        echo "for additional information and support"
-        newline
-        exit 1
-    fi
-elif ! $IS_RASPBIAN && [ $raspbianonly == "yes" ]; then
-    warning "Please only run this script on Raspbian on your Raspberry Pi"
+if ! $IS_ARMHF; then
+    warning "This hardware is not supported, sorry!"
     newline
     exit 1
-else
-    if [ $debugmode != "no" ]; then
+fi
+
+if ! $IS_SUPPORTED; then
+    warning "Your operating system is not supported, sorry!"
+    newline
+    exit 1
+fi
+
+if $IS_RASPBIAN && [ $raspbianonly == "yes" ]; then
+    raspbian_check
+    if [ $wheezysupport == "no" ] && $IS_WHEEZY || $IS_SQUEEZE; then
         newline
-        echo "IS_RASPBIAN is $IS_RASPBIAN"
-        echo "IS_MACOSX is $IS_MACOSX"
-        echo "IS_X86_64 is $IS_X86_64"
-        echo "IS_X86_32 is $IS_X86_32"
+        warning "--- Warning ---"
+        newline
+        echo "The $productname installer"
+        echo "does not work on this version of Raspbian."
+        echo "Check https://github.com/$gitusername/$gitreponame"
+        echo "for additional information and support"
+        newline
+        exit 1
     fi
 fi
 
@@ -455,7 +460,7 @@ elif $IS_ARMv6 && [ $armv6 == "no" ]; then
     warning "Sorry, your CPU is not supported by this installer"
     newline
     exit 1
-fi    
+fi
 
 if [ $forcesudo == "yes" ]; then
     sudocheck
@@ -516,8 +521,34 @@ if confirm "Do you wish to continue?"; then
             \curl -sS https://get.pimoroni.com/i2c | sudo bash -s - "-y"
             ASK_TO_REBOOT=true
         fi
+        if ! $IS_RASPBIAN; then
+            newline
+            echo "Checking packages required by interface..."
+            newline
+            if apt_pkg_req "i2c-tools"; then
+                DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
+                cd $DEBDIR
+                wget $RASPOOL/main/i/i2c-tools/i2c-tools_3.1.1+svn-2_armhf.deb &> /dev/null
+                sudo dpkg -i $DEBDIR/i2c-tools_3.1.1+svn-2_armhf.deb
+            fi
+            if apt_pkg_req "python-smbus"; then
+                DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
+                cd $DEBDIR
+                wget $RASPOOL/main/i/i2c-tools/python-smbus_3.1.1+svn-2_armhf.deb &> /dev/null
+                sudo dpkg -i $DEBDIR/python-smbus_3.1.1+svn-2_armhf.deb
+            fi
+            if apt_pkg_req "python3-smbus"; then
+                DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
+                cd $DEBDIR
+                wget $RASPOOL/main/i/i2c-tools/python3-smbus_3.1.1+svn-2_armhf.deb &> /dev/null
+                sudo dpkg -i $DEBDIR/python3-smbus_3.1.1+svn-2_armhf.deb
+                if python3 --version | grep "3.5" > /dev/null; then
+                    sudo cp /usr/lib/python3/dist-packages/smbus.cpython-34m-arm-linux-gnueabihf.so \
+                        /usr/lib/python3/dist-packages/smbus.cpython-35m-arm-linux-gnueabihf.so
+                fi
+            fi
+        fi
     fi
-    success "Done!"
     newline
 
 # minimum install routine
@@ -547,7 +578,7 @@ if confirm "Do you wish to continue?"; then
         echo "INSTALLDIR is $installdir"
     fi
 
-# raspbian repo install
+# apt repo install
 
     echo "Checking install requirements..."
 
@@ -588,7 +619,6 @@ if confirm "Do you wish to continue?"; then
         if [ $debpackage != "na" ]; then
             apt_pkg_install "$debpackage"
         fi
-        success "Done!"
     fi
 
 # pypi repo install
@@ -598,10 +628,10 @@ if confirm "Do you wish to continue?"; then
     for pipdep in ${pipdeplist[@]}
         do if pip_pkg_req "$pipdep"; then
             if [ $pip2support == "yes" ] && command -v python > /dev/null; then
-            sudo pip install "$pipdep"
+            sudo -H pip install "$pipdep"
             fi
             if [ $pip3support == "yes" ] && command -v python3 > /dev/null; then
-        sudo $PIP3_BIN install "$pipdep"
+        sudo -H $PIP3_BIN install "$pipdep"
             fi
         fi
     done
@@ -612,12 +642,11 @@ if confirm "Do you wish to continue?"; then
                 newline
                 echo "Installing $productname library for Python 2..."
                 newline
-                if ! sudo pip install $piplibname -U; then
+                if ! sudo -H pip install $piplibname -U; then
                     warning "Python 2 library install failed!"
                     echo "If problems persist, visit forums.pimoroni.com for support"
                     exit 1
                 fi
-                success "Done!"
             fi
         fi
         if [ $pip3support == "yes" ] && [ -n $(which python3) ]; then
@@ -625,7 +654,7 @@ if confirm "Do you wish to continue?"; then
                 newline
                 echo "Installing $productname library for Python 3..."
                 newline
-                    if ! sudo $PIP3_BIN install $piplibname -U; then
+                    if ! sudo -H $PIP3_BIN install $piplibname -U; then
                         warning "Python 3 library install failed!"
                     echo "If problems persist, visit forums.pimoroni.com for support"
                     exit 1
@@ -655,7 +684,7 @@ if confirm "Do you wish to continue?"; then
             if [ $debugmode != "no" ]; then
                 echo "git user name is $gitusername"
                 echo "git repo name is $gitreponame"
-            fi        
+            fi
             if [ $gitrepobranch != "master" ]; then
                 git clone https://github.com/$gitusername/$gitreponame $gitclonedir -b $gitrepobranch
             else
@@ -676,7 +705,6 @@ if confirm "Do you wish to continue?"; then
             sudo python3 ./setup.py install
         fi
         newline
-        success "Done!"
     fi
 
 # resources install
@@ -747,12 +775,10 @@ if confirm "Do you wish to continue?"; then
             done
             for moredep in ${morepipdep[@]}; do
                 if pip_pkg_req "$moredep"; then
-                    sudo pip install "$moredep"
-                    sudo $PIP3_BIN install "$moredep"
+                    sudo -H pip install "$moredep"
+                    sudo -H $PIP3_BIN install "$moredep"
                 fi
             done
-        else
-            success "Done!"
         fi
     fi
 
@@ -775,6 +801,11 @@ if confirm "Do you wish to continue?"; then
         echo "Finalising Install..."
         force_hdmi
         newline
+    fi
+
+    if $FAILED_PKG; then
+        newline
+        warning "Some packages could not be installed, review the output for details!"
     fi
 
     if [ $promptreboot == "yes" ] || $ASK_TO_REBOOT; then
