revision to PiTop detection

diff --git a/installers/unicornhat b/installers/unicornhat
--- a/installers/unicornhat
+++ b/installers/unicornhat
@@ -41,11 +41,8 @@ armv7="yes" # whether armv7 processors are supported
 armv8="yes" # whether armv8 processors are supported
 raspbianonly="no" # whether the script is allowed to run on other OSes
 osreleases=( "Raspbian" ) # list os-releases supported
-oswarning=( "Debian" "Ubuntu" ) # list experimental os-releases
-osdeny=( "Darwin" "Kali" "Mate" "PiTop" ) # list os-releases specifically disallowed
-squeezesupport="no" # whether Squeeze is supported
-wheezysupport="yes" # whether Wheezy is supported
-jessiesupport="yes" # whether Jessie is supported
+oswarning=( "Debian" "PiTop"  "Ubuntu" ) # list experimental os-releases
+osdeny=( "Darwin" "Kali" "Mate" ) # list os-releases specifically disallowed
 debpackage="na" # the name of the package in apt repo
 piplibname="unicornhat" # the name of the lib in pip repo
 pipoverride="yes" # whether the script should give priority to pip repo
@@ -71,7 +68,7 @@ moreaptdep=( "python-numpy" "python3-numpy" "python-flask" "python3-flask" ) # l
 pipdeplist=() # list of dependencies to source from pip
 morepipdep=() # list of additional pip dependencies
 
-# template 1609301205
+# template 1610112330
 
 FORCE=$1
 ASK_TO_REBOOT=false
@@ -186,7 +183,7 @@ os_check() {
 
     if [ -f /etc/os-release ]; then
         if cat /etc/os-release | grep "Raspbian" > /dev/null; then
-            IS_RASPBIAN=true && IS_SUPPORTED=true
+            IS_RASPBIAN=true
         fi
         if command -v apt-get > /dev/null; then
             for os in ${osreleases[@]}; do
@@ -206,7 +203,7 @@ os_check() {
             done
         fi
     fi
-    if [ -f ~/.pt-dashboard-config ]; then
+    if [ -f ~/.pt-dashboard-config ] || [ -d ~/.pt-dashboard ]; then
         IS_RASPBIAN=false
         for os in ${oswarning[@]}; do
             if [ $os == "PiTop" ]; then
@@ -237,29 +234,21 @@ os_check() {
 }
 
 raspbian_check() {
-    IS_SQUEEZE=false
-    IS_WHEEZY=false
-    IS_JESSIE=false
+    IS_SUPPORTED=false
+    IS_EXPERIMENTAL=false
 
     if [ -f /etc/os-release ]; then
-        if cat /etc/os-release | grep "jessie" > /dev/null; then
-            IS_JESSIE=true
+        if cat /etc/os-release | grep "/sid" > /dev/null; then
+            IS_SUPPORTED=false && IS_EXPERIMENTAL=true
+        elif cat /etc/os-release | grep "stretch" > /dev/null; then
+            IS_SUPPORTED=false && IS_EXPERIMENTAL=true
+        elif cat /etc/os-release | grep "jessie" > /dev/null; then
+            IS_SUPPORTED=true && IS_EXPERIMENTAL=false
         elif cat /etc/os-release | grep "wheezy" > /dev/null; then
-            IS_WHEEZY=true
-        elif cat /etc/os-release | grep "squeeze" > /dev/null; then
-            IS_SQUEEZE=true
+            IS_SUPPORTED=true && IS_EXPERIMENTAL=false
         else
-            echo "Unsupported distribution"
-            exit 1
+            IS_SUPPORTED=false && IS_EXPERIMENTAL=false
         fi
-    fi
-}
-
-raspbian_old() {
-    if $IS_SQUEEZE || $IS_WHEEZY ;then
-        true
-    else
-        false
     fi
 }
 
@@ -455,6 +444,7 @@ fi
 
 if ! $IS_ARMHF; then
     warning "This hardware is not supported, sorry!"
+    warning "Config files have been left untouched"
     newline && exit 1
 fi
 
@@ -476,7 +466,7 @@ fi
 
 if $IS_RASPBIAN; then
     raspbian_check
-    if [ $wheezysupport == "no" ] && raspbian_old; then
+    if ! $IS_SUPPORTED && ! $IS_EXPERIMENTAL; then
         newline && warning "--- Warning ---" && newline
         echo "The $productname installer"
         echo "does not work on this version of Raspbian."
@@ -850,7 +840,49 @@ if confirm "Do you wish to continue?"; then
     else # custom block starts here
         newline
         echo "Finalising Install..."
-        if $IS_RASPBIAN; then        
+        if $IS_RASPBIAN; then
+            warning "We need to reconfigure your audio configuration!"
+            echo "This is a necessary step to ensure $productname works correctly"
+            \curl -sS $GETPOOL/audio | sudo bash -s - "3"
+            ASK_TO_REBOOT=true
+            newline
+        fi
+    fi
+
+    if $FAILED_PKG; then
+        warning "Some packages could not be installed, review the output for details!"
+        newline
+    fi
+    if $IS_EXPERIMENTAL; then
+        warning "Support for your operating system is experimental. Please visit"
+        warning "forums.pimoroni.com if you experience issues with this product."
+        newline
+    fi
+
+    if [ "$FORCE" != '-y' ]; then
+        if [ $promptreboot == "yes" ] || $ASK_TO_REBOOT; then
+            sysreboot && newline
+        fi
+    fi
+else
+    newline && echo "Aborting..." && newline
+fi
+
+exit 0
+
+# script custom routines
+
+    if [ $customcmd == "no" ]; then
+        if [ -n "$pkgaptremove" ]; then
+            newline && echo "Finalising Install..." && newline
+            sysclean && newline
+        fi
+        newline && echo "All done!" && newline
+        echo "Enjoy your $productname!" && newline
+    else # custom block starts here
+        newline
+        echo "Finalising Install..."
+        if $IS_RASPBIAN; then
             warning "We need to reconfigure your audio configuration!"
             echo "This is a necessary step to ensure $productname works correctly"
             \curl -sS $GETPOOL/audio | sudo bash -s - "3"
