Unicornhat open to test on Kali

diff --git a/installers/unicornhat b/installers/unicornhat
--- a/installers/unicornhat
+++ b/installers/unicornhat
@@ -39,9 +39,9 @@ armhfonly="yes" # whether the script is allowed to run on other arch
 armv6="yes" # whether armv6 processors are supported
 armv7="yes" # whether armv7 processors are supported
 armv8="yes" # whether armv8 processors are supported
-raspbianonly="yes" # whether the script is allowed to run on other OSes
+raspbianonly="no" # whether the script is allowed to run on other OSes
 macosxsupport="no" # whether Mac OS X is supported by the script
-osreleases=( "Raspbian" "Debian" "Ubuntu" ) # list all the os-releases supported
+osreleases=( "Raspbian" "Debian" "Kali" "Mate" "Ubuntu" ) # list all the os-releases supported
 squeezesupport="no" # whether Squeeze is supported
 wheezysupport="yes" # whether Wheezy is supported
 jessiesupport="yes" # whether Jessie is supported
@@ -70,7 +70,7 @@ moreaptdep=( "python-numpy" "python3-numpy" "python-flask" "python3-flask" ) # l
 pipdeplist=() # list of dependencies to source from pip
 morepipdep=() # list of additional pip dependencies
 
-# template 1609082150
+# template 1609161600
 
 FORCE=$1
 ASK_TO_REBOOT=false
@@ -87,8 +87,9 @@ INITABCONF=/etc/inittab
 BLACKLIST=/etc/modprobe.d/raspi-blacklist.conf
 LOADMOD=/etc/modules
 
-RASPOOL="http://mirrordirector.raspbian.org/raspbian/pool"
 DEBPOOL="http://ftp.debian.org/debian/pool"
+GETPOOL="https://get.pimoroni.com"
+RASPOOL="http://mirrordirector.raspbian.org/raspbian/pool"
 
 # function define
 
@@ -250,12 +251,6 @@ servd_trig() {
     fi
 }
 
-servd_trig() {
-    if command -v service > /dev/null; then
-        sudo service $1 $2
-    fi
-}
-
 get_init_sys() {
     if command -v systemctl > /dev/null && systemctl | grep -q '\-\.mount'; then
         SYSTEMD=1
@@ -290,7 +285,7 @@ space_chk() {
             newline
             warning  "There is not enough space left to proceed with  installation"
             if confirm "Would you like to attempt to expand your filesystem?"; then
-                \curl -sS https://get.pimoroni.com/expandfs | sudo bash
+                \curl -sS $GETPOOL/expandfs | sudo bash
                 exit 1
             else
                 newline && exit 1
@@ -314,7 +309,7 @@ apt_pkg_req() {
 }
 
 apt_pkg_install() {
-    \curl -sS https://get.pimoroni.com/package | sudo bash -s - $1 || { warning "Apt failed to install $1!" && FAILED_PKG=true; }
+    \curl -sS $GETPOOL/package | sudo bash -s - $1 || { warning "Apt failed to install $1!" && FAILED_PKG=true; }
     newline
 }
 
@@ -395,7 +390,7 @@ else
     newline
     echo "If you want to see what this script does before"
     echo "running it, you should run:"
-    echo "\curl -sS https://get.pimoroni.com/$scriptname"
+    echo "\curl -sS $GETPOOL/$scriptname"
     newline
 fi
 
@@ -405,13 +400,10 @@ arch_check
 os_check
 home_dir
 check_network
+space_chk
 
 if [ $debugmode != "no" ]; then
     echo "USER_HOME is $USER_HOME" && newline
-fi
-
-if [ "$FORCE" != '-y' ]; then
-    space_chk
 fi
 
 if ! $IS_ARMHF; then
@@ -473,24 +465,35 @@ fi
 
 if confirm "Do you wish to continue?"; then
 
+# basic environment preparation
+
+    newline && echo "Checking environment..."
+
+    if ! command -v curl > /dev/null; then
+        apt_pkg_install "curl"
+    fi
+    if ! command -v apt-cache > /dev/null; then
+        apt_pkg_install "apt-cache"
+    fi
+    sysupdate
+    
+    if ! command -v pip > /dev/null; then
+        apt_pkg_install "python-pip"
+        apt_pkg_install "python3-pip"
+    fi
+    pip2_chk && pip3_chk
+
 # hardware setup
 
     newline && echo "Checking hardware requirements..."
 
-    if [ $uartreq == "yes" ]; then
-        newline && echo "The serial console must be disabled for $productname to work"
-        \curl -sS https://get.pimoroni.com/uarton | sudo bash -s - "-y"
-        ASK_TO_REBOOT=true && newline
-    fi
-
-    if [ $spireq == "yes" ]; then
-        newline
-        if ls /dev/spi* &> /dev/null; then
-            success "SPI already enabled"
-        else
-            echo "SPI must be enabled for $productname to work"
-            \curl -sS https://get.pimoroni.com/spi | sudo bash -s - "-y"
-            ASK_TO_REBOOT=true
+    if [ $gpioreq == "yes" ]; then
+        newline && echo "Checking for packages required for GPIO control..." && newline
+        if apt_pkg_req "python-rpi.gpio" && ! apt_pkg_install "python-rpi.gpio" &> /dev/null; then
+            sudo $PIP2_BIN install RPi.GPIO -U
+        fi
+        if apt_pkg_req "python3-rpi.gpio" && ! apt_pkg_install "python3-rpi.gpio" &> /dev/null; then
+            sudo $PIP3_BIN install RPi.GPIO -U
         fi
     fi
 
@@ -500,29 +503,59 @@ if confirm "Do you wish to continue?"; then
             success "I2C already enabled"
         else
             echo "I2C must be enabled for $productname to work"
-            \curl -sS https://get.pimoroni.com/i2c | sudo bash -s - "-y"
+            \curl -sS $GETPOOL/i2c | sudo bash -s - "-y"
             ASK_TO_REBOOT=true
         fi
-        newline && echo "Checking packages required by interface..." && newline
-        if apt_pkg_req "python-smbus" || apt_pkg_req "python3-smbus"; then
-            sysupdate
-            if apt_pkg_req "python-smbus"; then
-                if ! apt_pkg_install "python-smbus"  && python3 --version | grep "2.7" > /dev/null; then
-                    DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
-                    cd $DEBDIR
-                    wget $RASPOOL/main/i/i2c-tools/python-smbus_3.1.1+svn-2_armhf.deb &> /dev/null
-                    sudo dpkg -i $DEBDIR/python-smbus_3.1.1+svn-2_armhf.deb
-                fi
+        newline && echo "Checking packages required by I2C interface..." && newline
+        if apt_pkg_req "python-smbus"; then
+            if ! apt_pkg_install "python-smbus"  && python --version | grep "2.7" > /dev/null; then
+                DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
+                cd $DEBDIR
+                wget $RASPOOL/main/i/i2c-tools/python-smbus_3.1.1+svn-2_armhf.deb &> /dev/null
+                sudo dpkg -i $DEBDIR/python-smbus_3.1.1+svn-2_armhf.deb
             fi
-            if apt_pkg_req "python3-smbus"; then
-                if ! apt_pkg_install "python3-smbus" && python3 --version | grep "3.4" > /dev/null; then
+        fi
+        if apt_pkg_req "python3-smbus"; then
+            if ! apt_pkg_install "python3-smbus"; then
+                if python3 --version | grep "3.4" > /dev/null; then
                     DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
                     cd $DEBDIR
                     wget $RASPOOL/main/i/i2c-tools/python3-smbus_3.1.1+svn-2_armhf.deb &> /dev/null
                     sudo dpkg -i $DEBDIR/python3-smbus_3.1.1+svn-2_armhf.deb
+                elif python3 --version | grep "3.5" > /dev/null; then
+                    DEBDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
+                    cd $DEBDIR
+                    wget $GETPOOL/python3-smbus1_1.1+35dbg-1_armhf.deb &> /dev/null
+                    sudo dpkg -i $DEBDIR/python3-smbus1_1.1+35dbg-1_armhf.deb
+                else
+                    warning "Unable to install compatible python3-smbus!"
                 fi
             fi
         fi
+    fi
+
+    if [ $spireq == "yes" ]; then
+        newline
+        if ls /dev/spi* &> /dev/null; then
+            success "SPI already enabled"
+        else
+            echo "SPI must be enabled for $productname to work"
+            \curl -sS $GETPOOL/spi | sudo bash -s - "-y"
+            ASK_TO_REBOOT=true
+        fi
+        newline && echo "Checking packages required by SPI interface..." && newline
+        if apt_pkg_req "python-spidev" && ! apt_pkg_install "python-spidev" &> /dev/null; then
+            sudo $PIP2_BIN install spidev -U
+        fi
+        if apt_pkg_req "python3-spidev" && ! apt_pkg_install "python3-spidev" &> /dev/null; then
+            sudo $PIP3_BIN install spidev -U
+        fi
+    fi
+
+    if [ $uartreq == "yes" ]; then
+        newline && echo "The serial console must be disabled for $productname to work"
+        \curl -sS $GETPOOL/uarton | sudo bash -s - "-y"
+        ASK_TO_REBOOT=true && newline
     fi
 
 # minimum install routine
@@ -530,7 +563,7 @@ if confirm "Do you wish to continue?"; then
     if [ $gitrepoclone != "yes" ]; then
         newline
         echo "$productname comes with examples and documentation that you may wish to install."
-        echo "Performing a full install with ensure those resources are installed,"
+        echo "Performing a full install will ensure those resources are installed,"
         echo "along with all required dependencies. It may however take a while!"
         newline
 
@@ -556,34 +589,30 @@ if confirm "Do you wish to continue?"; then
 
     echo "Checking install requirements..."
 
-    if command -v apt-get > /dev/null; then
-        newline && echo "Updating package indexes..."
-        sysupdate
-        newline && echo "Checking for dependencies..."
+    newline && echo "Updating package indexes..."
+    newline && echo "Checking for dependencies..."
 
-        if $REMOVE_PKG; then
-            for pkgrm in ${pkgaptremove[@]}; do
-                warning "Installed package conflicts with requirements"
-                sudo apt-get remove "$pkgrm"
-            done
-        fi
-
-        pkgdeplist=( "${pkgdeplist1[@]}" "${pkgdeplist2[@]}" "${pkgdeplist3[@]}" )
-
-        for pkgdep in ${pkgdeplist[@]}; do
-            if apt_pkg_req "$pkgdep"; then
-                apt_pkg_install "$pkgdep"
-            fi
+    if $REMOVE_PKG; then
+        for pkgrm in ${pkgaptremove[@]}; do
+            warning "Installed package conflicts with requirements"
+            sudo apt-get remove "$pkgrm"
         done
-        if [ $debpackage != "na" ]; then
-            apt_pkg_install "$debpackage"
+    fi
+
+    pkgdeplist=( "${pkgdeplist1[@]}" "${pkgdeplist2[@]}" "${pkgdeplist3[@]}" )
+
+    for pkgdep in ${pkgdeplist[@]}; do
+        if apt_pkg_req "$pkgdep"; then
+            apt_pkg_install "$pkgdep"
         fi
+    done
+    if [ $debpackage != "na" ]; then
+        apt_pkg_install "$debpackage"
     fi
 
 # pypi repo install
 
     if [ $pip2support == "yes" ] && [ -n $(which python2) ]; then
-        pip2_chk
         for pipdep in ${pipdeplist[@]}; do
             if pip2_pkg_req "$pipdep"; then
                 sudo -H $PIP2_BIN install "$pipdep"
@@ -600,7 +629,6 @@ if confirm "Do you wish to continue?"; then
     fi
 
     if [ $pip3support == "yes" ] && [ -n $(which python3) ]; then
-        pip3_chk
         for pipdep in ${pipdeplist[@]}; do
             if pip3_pkg_req "$pipdep"; then
                 sudo -H $PIP3_BIN install "$pipdep"
@@ -744,23 +772,17 @@ if confirm "Do you wish to continue?"; then
 
     if [ $customcmd == "no" ]; then
         if [ -n "$pkgaptremove" ]; then
-            newline
-            echo "Finalising Install..."
-            newline
-            sysclean
-            newline
+            newline && echo "Finalising Install..." && newline
+            sysclean && newline
         fi
-        newline
-        success "All done!"
-        newline
-        echo "Enjoy your $productname!"
-        newline
+        newline && success "All done!" && newline
+        echo "Enjoy your $productname!" && newline
     else # custom block starts here
         newline
         echo "Finalising Install..."
         warning "We need to reconfigure your audio configuration!"
         echo "This is a necessary step to ensure $productname works correctly"
-        \curl -sS https://get.pimoroni.com/audio | sudo bash -s - "3"
+        \curl -sS $GETPOOL/audio | sudo bash -s - "3"
         ASK_TO_REBOOT=true
         newline
     fi
@@ -771,13 +793,10 @@ if confirm "Do you wish to continue?"; then
     fi
 
     if [ $promptreboot == "yes" ] || $ASK_TO_REBOOT; then
-        sysreboot
-        newline
+        sysreboot && newline
     fi
 else
-    newline
-    echo "Aborting..."
-    newline
+    newline && echo "Aborting..." && newline
 fi
 
 exit 0
