adding hifiberry dtoverlay in custom block rather i2s setup

diff --git a/installers/wifiroaming b/installers/wifiroaming
--- a/installers/wifiroaming
+++ b/installers/wifiroaming
@@ -21,56 +21,56 @@ DISCLAIMER
 
 # script control variables
 
-productname="Speaker pHAT" # the name of the product to install
-scriptname="speakerphat" # the name of this script
+productname="WiFi AP mode" # the name of the product to install
+scriptname="wifiapmode" # the name of this script
 spacereq=50 # minimum size required on root partition in MB
 debugmode="no" # whether the script should use debug routines
 debuguser="none" # optional test git user to use in debug mode
 debugpoint="none" # optional git repo branch or tag to checkout
 forcesudo="no" # whether the script requires to be ran with root privileges
-promptreboot="no" # whether the script should always prompt user to reboot
-mininstall="no" # whether the script enforces minimum install routine
+promptreboot="yes" # whether the script should always prompt user to reboot
+mininstall="yes" # whether the script enforces minimum install routine
 customcmd="yes" # whether to execute commands specified before exit
-gpioreq="yes" # whether low-level gpio access is required
-i2creq="yes" # whether the i2c interface is required
-i2sreq="yes" # whether the i2s interface is required
+gpioreq="no" # whether low-level gpio access is required
+i2creq="no" # whether the i2c interface is required
+i2sreq="no" # whether the i2s interface is required
 spireq="no" # whether the spi interface is required
 uartreq="no" # whether uart communication is required
 armhfonly="yes" # whether the script is allowed to run on other arch
 armv6="yes" # whether armv6 processors are supported
 armv7="yes" # whether armv7 processors are supported
 armv8="yes" # whether armv8 processors are supported
-raspbianonly="no" # whether the script is allowed to run on other OSes
+raspbianonly="yes" # whether the script is allowed to run on other OSes
 osreleases=( "Raspbian" ) # list os-releases supported
-oswarning=( "Debian" "Mate" "PiTop" "RetroPie" "Ubuntu" "Volumio" ) # list experimental os-releases
-osdeny=( "Darwin" "Kali" "Linaro" ) # list os-releases specifically disallowed
-debpackage="sn3218" # the name of the package in apt repo
-piplibname="sn3218" # the name of the lib in pip repo
+oswarning=( "Debian" "Kano" "PiTop" "RetroPie" "Ubuntu" ) # list experimental os-releases
+osdeny=( "Darwin" "Kali" "Linaro" "Mate" "Volumio" ) # list os-releases specifically disallowed
+debpackage="na" # the name of the package in apt repo
+piplibname="na" # the name of the lib in pip repo
 pipoverride="no" # whether the script should give priority to pip repo
-pip2support="yes" # whether python2 is supported
-pip3support="yes" # whether python3 is supported
-topdir="Pimoroni" # the name of the top level directory
-localdir="speakerphat" # the name of the dir for copy of resources
-gitreponame="speaker-phat" # the name of the git project repo
-gitusername="pimoroni" # the name of the git user to fetch repo from
-gitrepobranch="master" # repo branch to checkout
-gitrepotop="root" # the name of the dir to base repo from
+pip2support="no" # whether python2 is supported
+pip3support="no" # whether python3 is supported
+topdir="na" # the name of the top level directory
+localdir="na" # the name of the dir for copy of resources
+gitreponame="na" # the name of the git project repo
+gitusername="na" # the name of the git user to fetch repo from
+gitrepobranch="na" # repo branch to checkout
+gitrepotop="na" # the name of the dir to base repo from
 gitrepoclone="no" # whether the git repo is to be cloned locally
-gitclonedir="source" # the name of the local dir for repo
-repoclean="no"  # whether any git repo clone found should be cleaned up
+gitclonedir="na" # the name of the local dir for repo
+repoclean="no" # whether any git repo clone found should be cleaned up
 repoinstall="no" # whether the library should be installed from repo
 libdir="na" # subdirectory of library in repo
-copydir=( "python" "test" ) # subdirectories to copy from repo
-copyhead="yes" # whether to use the latest repo commit or release tag
+copydir=() # subdirectories to copy from repo
+copyhead="no" # whether to use the latest repo commit or release tag
 pkgremove=() # list of conflicting packages to remove
-coredeplist=( "alsa-utils" "espeak" "wiringpi" ) # list of core dependencies
+coredeplist=( "iw" "wpasupplicant" "hostapd" "dnsmasq" ) # list of core dependencies
 pythondep=() # list of python dependencies
 pipdeplist=() # list of dependencies to source from pypi
 examplesdep=() # list of python modules required by examples
 somemoredep=() # list of additional dependencies
 xdisplaydep=() # list of dependencies requiring X server
 
-# template 1703292105
+# template 1703291225
 
 FORCE=$1
 ASK_TO_REBOOT=false
@@ -591,9 +591,7 @@ if [ $i2creq == "yes" ]; then
 fi
 if [ $i2sreq == "yes" ]; then
     echo -e "Note: $productname uses the I2S interface"
-    if [ $OS_NAME != "Volumio" ]; then
-        warning "The on-board audio chip will be disabled if you proceed!"
-    fi
+    warning "The on-board audio chip will be disabled if you proceed!"
 fi
 
 newline
@@ -811,6 +809,7 @@ if confirm "Do you wish to continue?"; then
 
     if [ $i2sreq == "yes" ]; then
         add_dtoverlay i2s-mmap
+        add_dtoverlay hifiberry-dac
         if [ -f /etc/asound.conf ]; then
             sudo rm -f /etc/asound.conf.backup &> /dev/null
             sudo mv /etc/asound.conf /etc/asound.conf.backup
@@ -1073,39 +1072,96 @@ if confirm "Do you wish to continue?"; then
         echo -e "\nAll done. Enjoy your $productname!\n"
     else # custom block starts here
         echo -e "\nFinalising Install...\n"
-        add_dtoverlay hifiberry-dac
-        if [ $OS_NAME != "Volumio" ]; then
-            disable_pi_audio
-        fi
-        if [ $OS_NAME == "Raspbian" ]; then
-            kill_volumealsa && disable_pulseaudio
-        fi
-        cd $USER_HOME/$topdir
-        if [ -d $USER_HOME/$topdir/pivumeter ]; then
-            cd ./pivumeter && git pull
+        if [ $(grep -c "^denyinterfaces wlan0" /etc/dhcpcd.conf) -ge 1 ]; then
+            inform "This Raspberry Pi seems to be in AP mode already!"
+            if prompt "Would you like to redefine the SSDI and password?"; then
+                apssid=$(hostname)
+                sudo sed -i "s|^ssid=.*$|ssid=$apssid|" /etc/hostapd/hostapd.conf
+                inform "SSDI set to $apssid (hostname)"
+                read -r -p "Password to join network (8 characters minimum): " ssidpass < /dev/tty
+                if [ ${#ssidpass} -ge 8 ]; then
+                    sudo sed -i "s|^wpa_passphrase=.*$|wpa_passphrase=$ssidpass|" /etc/hostapd/hostapd.conf
+                else
+                    sudo sed -i "s|^wpa_passphrase=.*$|wpa_passphrase=raspberry|" /etc/hostapd/hostapd.conf
+                    inform "Not enough characters, password set to 'raspberry'!"
+                fi
+                echo && sysreboot && echo && exit 1
+            elif prompt "Do you want to disable AP mode?"; then
+                echo
+                sudo sed -i "/^denyinterfaces wlan0$/ s|^|#|" /etc/dhcpcd.conf
+                sudo sed -i "/^source-directory.*/ s|^|#|" /etc/network/interfaces
+                sudo sed -i "/^#allow-hotplug wlan0$/,+2 s|#||" /etc/network/interfaces
+                sudo systemctl disable hostapd
+                sudo systemctl disable dnsmasq
+                echo && sysreboot && echo && exit 1
+            else
+                echo -e "Nothing to do then!\n" && exit 1
+            fi
         else
-            git clone --depth=1 https://github.com/$gitusername/pivumeter && cd ./pivumeter
+            if [ $(grep -c "denyinterfaces wlan0" /etc/dhcpcd.conf) -eq 0 ]; then
+                sudo bash -c 'echo -e "\n#Configuration for AP mode\ndenyinterfaces wlan0" >> /etc/dhcpcd.conf'
+            else
+                sudo sed -i "s|.*denyinterfaces wlan0$|denyinterfaces wlan0|" /etc/dhcpcd.conf
+            fi
+            sudo bash -c 'cat > /etc/dnsmasq.d/wlan0ap.conf <<EOF
+interface=wlan0
+dhcp-range=10.0.0.2,10.0.0.12,255.255.255.0,12h
+EOF'
+            sudo sed -i "s|.*source-directory.*|source-directory /etc/network/interfaces.d|" /etc/network/interfaces
+            sudo sed -i "/^allow-hotplug wlan0$/,+2 s|^|#|" /etc/network/interfaces
+            sudo bash -c 'cat > /etc/network/interfaces.d/wlan0static <<EOF
+allow-hotplug wlan0
+iface wlan0 inet static
+	address 10.0.0.1
+	netmask 255.255.255.0
+	network 10.0.0.0
+	broadcast 10.0.0.255
+EOF'
+            sudo sed -i 's|.*DAEMON_CONF=.*|DAEMON_CONF="/etc/hostapd/hostapd.conf"|' /etc/default/hostapd
+            sudo mv -f /etc/hostapd/hostapd.conf /etc/hostapd/hostapd.conf.backup &> /dev/null
+            sudo bash -c 'cat > /etc/hostapd/hostapd.conf <<EOF
+interface=wlan0
+hw_mode=g
+channel=10
+auth_algs=1
+ssid=raspberrypi
+wpa_passphrase=raspberry
+wpa=2
+wpa_key_mgmt=WPA-PSK
+wpa_pairwise=CCMP
+rsn_pairwise=CCMP
+EOF'
+            apssid=$(hostname)
+            sudo sed -i "s|^ssid=.*$|ssid=$apssid|" /etc/hostapd/hostapd.conf
+            inform "SSDI set to $apssid (hostname)"
+            read -r -p "Password to join network (8 characters minimum): " ssidpass < /dev/tty
+            if [ ${#ssidpass} -ge 8 ]; then
+                sudo sed -i "s|^wpa_passphrase=.*$|wpa_passphrase=$ssidpass|" /etc/hostapd/hostapd.conf
+            else
+                sudo sed -i "s|^wpa_passphrase=.*$|wpa_passphrase=raspberry|" /etc/hostapd/hostapd.conf
+                inform "Not enough characters, password set to 'raspberry'!"
+            fi
+            sudo systemctl enable hostapd
+            sudo systemctl enable dnsmasq
+            echo
         fi
-        sudo bash ./setup.sh -y speaker-phat
     fi
 
     if $FAILED_PKG; then
-        warning "Some packages could not be installed, review the output for details!"
-        newline
+        warning "Some packages could not be installed, review the output for details!\n"
     fi
     if $IS_EXPERIMENTAL; then
         warning "Support for your operating system is experimental. Please visit"
-        warning "forums.pimoroni.com if you experience issues with this product."
-        newline
+        warning "forums.pimoroni.com if you experience issues with this product.\n"
     fi
 
-    if [ "$1" != '-y' ]; then
+    if [ "$FORCE" != '-y' ]; then
         if [ $promptreboot == "yes" ] || $ASK_TO_REBOOT; then
             sysreboot && newline
         fi
     fi
 else
-    newline && echo "Aborting..." && newline
+    echo -e "\nAborting...\n"
 fi
 
 exit 0
